package plutus

// ID represents an id managed and generated by plutus
type ID string

// PaymentsEngine is the core engine of plutus
type PaymentsEngine struct {
	Bridge     *PaymentBridge
	Repository *Repository
}
