package plutus

// ID represents an id managed and generated by plutus
type ID string

// SalesEngine is the core engine of plutus
type SalesEngine struct {
	Company          *Company
	Bridge           PaymentBridge
	Repository       Repository
	DeliveryChannels []DeliveryChannel
}
