// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/plutus.proto

package plutus

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CardTokenType int32

const (
	CardTokenType_ONEUSE    CardTokenType = 0
	CardTokenType_RECURRENT CardTokenType = 1
)

var CardTokenType_name = map[int32]string{
	0: "ONEUSE",
	1: "RECURRENT",
}

var CardTokenType_value = map[string]int32{
	"ONEUSE":    0,
	"RECURRENT": 1,
}

func (x CardTokenType) String() string {
	return proto.EnumName(CardTokenType_name, int32(x))
}

func (CardTokenType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{0}
}

type SaleState int32

const (
	SaleState_NULL    SaleState = 0
	SaleState_DRAFT   SaleState = 1
	SaleState_SIGNED  SaleState = 2
	SaleState_PAIDOUT SaleState = 3
	SaleState_DONE    SaleState = 4
)

var SaleState_name = map[int32]string{
	0: "NULL",
	1: "DRAFT",
	2: "SIGNED",
	3: "PAIDOUT",
	4: "DONE",
}

var SaleState_value = map[string]int32{
	"NULL":    0,
	"DRAFT":   1,
	"SIGNED":  2,
	"PAIDOUT": 3,
	"DONE":    4,
}

func (x SaleState) String() string {
	return proto.EnumName(SaleState_name, int32(x))
}

func (SaleState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{1}
}

type DiscountType int32

const (
	DiscountType_STATIC  DiscountType = 0
	DiscountType_PERCENT DiscountType = 1
)

var DiscountType_name = map[int32]string{
	0: "STATIC",
	1: "PERCENT",
}

var DiscountType_value = map[string]int32{
	"STATIC":  0,
	"PERCENT": 1,
}

func (x DiscountType) String() string {
	return proto.EnumName(DiscountType_name, int32(x))
}

func (DiscountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{2}
}

type DiscountCodeValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	CustomerID           string   `protobuf:"bytes,2,opt,name=customerID,proto3" json:"customerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountCodeValue) Reset()         { *m = DiscountCodeValue{} }
func (m *DiscountCodeValue) String() string { return proto.CompactTextString(m) }
func (*DiscountCodeValue) ProtoMessage()    {}
func (*DiscountCodeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{0}
}

func (m *DiscountCodeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountCodeValue.Unmarshal(m, b)
}
func (m *DiscountCodeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountCodeValue.Marshal(b, m, deterministic)
}
func (m *DiscountCodeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountCodeValue.Merge(m, src)
}
func (m *DiscountCodeValue) XXX_Size() int {
	return xxx_messageInfo_DiscountCodeValue.Size(m)
}
func (m *DiscountCodeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountCodeValue.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountCodeValue proto.InternalMessageInfo

func (m *DiscountCodeValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *DiscountCodeValue) GetCustomerID() string {
	if m != nil {
		return m.CustomerID
	}
	return ""
}

type DiscountCodeExist struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountCodeExist) Reset()         { *m = DiscountCodeExist{} }
func (m *DiscountCodeExist) String() string { return proto.CompactTextString(m) }
func (*DiscountCodeExist) ProtoMessage()    {}
func (*DiscountCodeExist) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{1}
}

func (m *DiscountCodeExist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountCodeExist.Unmarshal(m, b)
}
func (m *DiscountCodeExist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountCodeExist.Marshal(b, m, deterministic)
}
func (m *DiscountCodeExist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountCodeExist.Merge(m, src)
}
func (m *DiscountCodeExist) XXX_Size() int {
	return xxx_messageInfo_DiscountCodeExist.Size(m)
}
func (m *DiscountCodeExist) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountCodeExist.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountCodeExist proto.InternalMessageInfo

func (m *DiscountCodeExist) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ChargeWithNativeToken struct {
	SaleID               string   `protobuf:"bytes,1,opt,name=saleID,proto3" json:"saleID,omitempty"`
	NativeToken          string   `protobuf:"bytes,2,opt,name=nativeToken,proto3" json:"nativeToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeWithNativeToken) Reset()         { *m = ChargeWithNativeToken{} }
func (m *ChargeWithNativeToken) String() string { return proto.CompactTextString(m) }
func (*ChargeWithNativeToken) ProtoMessage()    {}
func (*ChargeWithNativeToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{2}
}

func (m *ChargeWithNativeToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeWithNativeToken.Unmarshal(m, b)
}
func (m *ChargeWithNativeToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeWithNativeToken.Marshal(b, m, deterministic)
}
func (m *ChargeWithNativeToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeWithNativeToken.Merge(m, src)
}
func (m *ChargeWithNativeToken) XXX_Size() int {
	return xxx_messageInfo_ChargeWithNativeToken.Size(m)
}
func (m *ChargeWithNativeToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeWithNativeToken.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeWithNativeToken proto.InternalMessageInfo

func (m *ChargeWithNativeToken) GetSaleID() string {
	if m != nil {
		return m.SaleID
	}
	return ""
}

func (m *ChargeWithNativeToken) GetNativeToken() string {
	if m != nil {
		return m.NativeToken
	}
	return ""
}

type DiscountCodes struct {
	Discounts            []*DiscountCode `protobuf:"bytes,1,rep,name=discounts,proto3" json:"discounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DiscountCodes) Reset()         { *m = DiscountCodes{} }
func (m *DiscountCodes) String() string { return proto.CompactTextString(m) }
func (*DiscountCodes) ProtoMessage()    {}
func (*DiscountCodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{3}
}

func (m *DiscountCodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountCodes.Unmarshal(m, b)
}
func (m *DiscountCodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountCodes.Marshal(b, m, deterministic)
}
func (m *DiscountCodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountCodes.Merge(m, src)
}
func (m *DiscountCodes) XXX_Size() int {
	return xxx_messageInfo_DiscountCodes.Size(m)
}
func (m *DiscountCodes) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountCodes.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountCodes proto.InternalMessageInfo

func (m *DiscountCodes) GetDiscounts() []*DiscountCode {
	if m != nil {
		return m.Discounts
	}
	return nil
}

type ActiveDiscountsRequest struct {
	Until                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=until,proto3" json:"until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ActiveDiscountsRequest) Reset()         { *m = ActiveDiscountsRequest{} }
func (m *ActiveDiscountsRequest) String() string { return proto.CompactTextString(m) }
func (*ActiveDiscountsRequest) ProtoMessage()    {}
func (*ActiveDiscountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{4}
}

func (m *ActiveDiscountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveDiscountsRequest.Unmarshal(m, b)
}
func (m *ActiveDiscountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveDiscountsRequest.Marshal(b, m, deterministic)
}
func (m *ActiveDiscountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveDiscountsRequest.Merge(m, src)
}
func (m *ActiveDiscountsRequest) XXX_Size() int {
	return xxx_messageInfo_ActiveDiscountsRequest.Size(m)
}
func (m *ActiveDiscountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveDiscountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveDiscountsRequest proto.InternalMessageInfo

func (m *ActiveDiscountsRequest) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type DiscountCodeID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountCodeID) Reset()         { *m = DiscountCodeID{} }
func (m *DiscountCodeID) String() string { return proto.CompactTextString(m) }
func (*DiscountCodeID) ProtoMessage()    {}
func (*DiscountCodeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{5}
}

func (m *DiscountCodeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountCodeID.Unmarshal(m, b)
}
func (m *DiscountCodeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountCodeID.Marshal(b, m, deterministic)
}
func (m *DiscountCodeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountCodeID.Merge(m, src)
}
func (m *DiscountCodeID) XXX_Size() int {
	return xxx_messageInfo_DiscountCodeID.Size(m)
}
func (m *DiscountCodeID) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountCodeID.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountCodeID proto.InternalMessageInfo

func (m *DiscountCodeID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DiscountCodeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountCodeRequest) Reset()         { *m = DiscountCodeRequest{} }
func (m *DiscountCodeRequest) String() string { return proto.CompactTextString(m) }
func (*DiscountCodeRequest) ProtoMessage()    {}
func (*DiscountCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{6}
}

func (m *DiscountCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountCodeRequest.Unmarshal(m, b)
}
func (m *DiscountCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountCodeRequest.Marshal(b, m, deterministic)
}
func (m *DiscountCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountCodeRequest.Merge(m, src)
}
func (m *DiscountCodeRequest) XXX_Size() int {
	return xxx_messageInfo_DiscountCodeRequest.Size(m)
}
func (m *DiscountCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountCodeRequest proto.InternalMessageInfo

type SaleUpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdateData           *Sale    `protobuf:"bytes,2,opt,name=updateData,proto3" json:"updateData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaleUpdateRequest) Reset()         { *m = SaleUpdateRequest{} }
func (m *SaleUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*SaleUpdateRequest) ProtoMessage()    {}
func (*SaleUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{7}
}

func (m *SaleUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaleUpdateRequest.Unmarshal(m, b)
}
func (m *SaleUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaleUpdateRequest.Marshal(b, m, deterministic)
}
func (m *SaleUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaleUpdateRequest.Merge(m, src)
}
func (m *SaleUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_SaleUpdateRequest.Size(m)
}
func (m *SaleUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaleUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaleUpdateRequest proto.InternalMessageInfo

func (m *SaleUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SaleUpdateRequest) GetUpdateData() *Sale {
	if m != nil {
		return m.UpdateData
	}
	return nil
}

type DeliverSaleRequest struct {
	Sale                 *SaleIDRequest   `protobuf:"bytes,1,opt,name=sale,proto3" json:"sale,omitempty"`
	Channel              *DeliveryChannel `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeliverSaleRequest) Reset()         { *m = DeliverSaleRequest{} }
func (m *DeliverSaleRequest) String() string { return proto.CompactTextString(m) }
func (*DeliverSaleRequest) ProtoMessage()    {}
func (*DeliverSaleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{8}
}

func (m *DeliverSaleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverSaleRequest.Unmarshal(m, b)
}
func (m *DeliverSaleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverSaleRequest.Marshal(b, m, deterministic)
}
func (m *DeliverSaleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverSaleRequest.Merge(m, src)
}
func (m *DeliverSaleRequest) XXX_Size() int {
	return xxx_messageInfo_DeliverSaleRequest.Size(m)
}
func (m *DeliverSaleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverSaleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverSaleRequest proto.InternalMessageInfo

func (m *DeliverSaleRequest) GetSale() *SaleIDRequest {
	if m != nil {
		return m.Sale
	}
	return nil
}

func (m *DeliverSaleRequest) GetChannel() *DeliveryChannel {
	if m != nil {
		return m.Channel
	}
	return nil
}

type DeliverChannelResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliverChannelResponse) Reset()         { *m = DeliverChannelResponse{} }
func (m *DeliverChannelResponse) String() string { return proto.CompactTextString(m) }
func (*DeliverChannelResponse) ProtoMessage()    {}
func (*DeliverChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{9}
}

func (m *DeliverChannelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverChannelResponse.Unmarshal(m, b)
}
func (m *DeliverChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverChannelResponse.Marshal(b, m, deterministic)
}
func (m *DeliverChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverChannelResponse.Merge(m, src)
}
func (m *DeliverChannelResponse) XXX_Size() int {
	return xxx_messageInfo_DeliverChannelResponse.Size(m)
}
func (m *DeliverChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverChannelResponse proto.InternalMessageInfo

func (m *DeliverChannelResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeliverChannelResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type DeliveryChannel struct {
	// Types that are valid to be assigned to Identification:
	//	*DeliveryChannel_Id
	//	*DeliveryChannel_Name
	//	*DeliveryChannel_Code
	Identification       isDeliveryChannel_Identification `protobuf_oneof:"identification"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *DeliveryChannel) Reset()         { *m = DeliveryChannel{} }
func (m *DeliveryChannel) String() string { return proto.CompactTextString(m) }
func (*DeliveryChannel) ProtoMessage()    {}
func (*DeliveryChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{10}
}

func (m *DeliveryChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryChannel.Unmarshal(m, b)
}
func (m *DeliveryChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryChannel.Marshal(b, m, deterministic)
}
func (m *DeliveryChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryChannel.Merge(m, src)
}
func (m *DeliveryChannel) XXX_Size() int {
	return xxx_messageInfo_DeliveryChannel.Size(m)
}
func (m *DeliveryChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryChannel.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryChannel proto.InternalMessageInfo

type isDeliveryChannel_Identification interface {
	isDeliveryChannel_Identification()
}

type DeliveryChannel_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type DeliveryChannel_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

type DeliveryChannel_Code struct {
	Code string `protobuf:"bytes,3,opt,name=code,proto3,oneof"`
}

func (*DeliveryChannel_Id) isDeliveryChannel_Identification() {}

func (*DeliveryChannel_Name) isDeliveryChannel_Identification() {}

func (*DeliveryChannel_Code) isDeliveryChannel_Identification() {}

func (m *DeliveryChannel) GetIdentification() isDeliveryChannel_Identification {
	if m != nil {
		return m.Identification
	}
	return nil
}

func (m *DeliveryChannel) GetId() string {
	if x, ok := m.GetIdentification().(*DeliveryChannel_Id); ok {
		return x.Id
	}
	return ""
}

func (m *DeliveryChannel) GetName() string {
	if x, ok := m.GetIdentification().(*DeliveryChannel_Name); ok {
		return x.Name
	}
	return ""
}

func (m *DeliveryChannel) GetCode() string {
	if x, ok := m.GetIdentification().(*DeliveryChannel_Code); ok {
		return x.Code
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeliveryChannel) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeliveryChannel_Id)(nil),
		(*DeliveryChannel_Name)(nil),
		(*DeliveryChannel_Code)(nil),
	}
}

type SaleIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaleIDRequest) Reset()         { *m = SaleIDRequest{} }
func (m *SaleIDRequest) String() string { return proto.CompactTextString(m) }
func (*SaleIDRequest) ProtoMessage()    {}
func (*SaleIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{11}
}

func (m *SaleIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaleIDRequest.Unmarshal(m, b)
}
func (m *SaleIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaleIDRequest.Marshal(b, m, deterministic)
}
func (m *SaleIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaleIDRequest.Merge(m, src)
}
func (m *SaleIDRequest) XXX_Size() int {
	return xxx_messageInfo_SaleIDRequest.Size(m)
}
func (m *SaleIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaleIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaleIDRequest proto.InternalMessageInfo

func (m *SaleIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FastSale struct {
	CustomerEmail        string     `protobuf:"bytes,1,opt,name=customerEmail,proto3" json:"customerEmail,omitempty"`
	Products             []*Product `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FastSale) Reset()         { *m = FastSale{} }
func (m *FastSale) String() string { return proto.CompactTextString(m) }
func (*FastSale) ProtoMessage()    {}
func (*FastSale) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{12}
}

func (m *FastSale) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FastSale.Unmarshal(m, b)
}
func (m *FastSale) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FastSale.Marshal(b, m, deterministic)
}
func (m *FastSale) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastSale.Merge(m, src)
}
func (m *FastSale) XXX_Size() int {
	return xxx_messageInfo_FastSale.Size(m)
}
func (m *FastSale) XXX_DiscardUnknown() {
	xxx_messageInfo_FastSale.DiscardUnknown(m)
}

var xxx_messageInfo_FastSale proto.InternalMessageInfo

func (m *FastSale) GetCustomerEmail() string {
	if m != nil {
		return m.CustomerEmail
	}
	return ""
}

func (m *FastSale) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type NewSaleRequest struct {
	Customer             *Customer  `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Products             []*Product `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NewSaleRequest) Reset()         { *m = NewSaleRequest{} }
func (m *NewSaleRequest) String() string { return proto.CompactTextString(m) }
func (*NewSaleRequest) ProtoMessage()    {}
func (*NewSaleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{13}
}

func (m *NewSaleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSaleRequest.Unmarshal(m, b)
}
func (m *NewSaleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSaleRequest.Marshal(b, m, deterministic)
}
func (m *NewSaleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSaleRequest.Merge(m, src)
}
func (m *NewSaleRequest) XXX_Size() int {
	return xxx_messageInfo_NewSaleRequest.Size(m)
}
func (m *NewSaleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSaleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewSaleRequest proto.InternalMessageInfo

func (m *NewSaleRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *NewSaleRequest) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type CardTokenByID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardTokenByID) Reset()         { *m = CardTokenByID{} }
func (m *CardTokenByID) String() string { return proto.CompactTextString(m) }
func (*CardTokenByID) ProtoMessage()    {}
func (*CardTokenByID) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{14}
}

func (m *CardTokenByID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardTokenByID.Unmarshal(m, b)
}
func (m *CardTokenByID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardTokenByID.Marshal(b, m, deterministic)
}
func (m *CardTokenByID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardTokenByID.Merge(m, src)
}
func (m *CardTokenByID) XXX_Size() int {
	return xxx_messageInfo_CardTokenByID.Size(m)
}
func (m *CardTokenByID) XXX_DiscardUnknown() {
	xxx_messageInfo_CardTokenByID.DiscardUnknown(m)
}

var xxx_messageInfo_CardTokenByID proto.InternalMessageInfo

func (m *CardTokenByID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CardTokenByCustomer struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CardTokenByCustomer) Reset()         { *m = CardTokenByCustomer{} }
func (m *CardTokenByCustomer) String() string { return proto.CompactTextString(m) }
func (*CardTokenByCustomer) ProtoMessage()    {}
func (*CardTokenByCustomer) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{15}
}

func (m *CardTokenByCustomer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardTokenByCustomer.Unmarshal(m, b)
}
func (m *CardTokenByCustomer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardTokenByCustomer.Marshal(b, m, deterministic)
}
func (m *CardTokenByCustomer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardTokenByCustomer.Merge(m, src)
}
func (m *CardTokenByCustomer) XXX_Size() int {
	return xxx_messageInfo_CardTokenByCustomer.Size(m)
}
func (m *CardTokenByCustomer) XXX_DiscardUnknown() {
	xxx_messageInfo_CardTokenByCustomer.DiscardUnknown(m)
}

var xxx_messageInfo_CardTokenByCustomer proto.InternalMessageInfo

func (m *CardTokenByCustomer) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type NewCardTokenRequest struct {
	Card                 *Card         `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	Customer             *Customer     `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	Type                 CardTokenType `protobuf:"varint,3,opt,name=type,proto3,enum=CardTokenType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NewCardTokenRequest) Reset()         { *m = NewCardTokenRequest{} }
func (m *NewCardTokenRequest) String() string { return proto.CompactTextString(m) }
func (*NewCardTokenRequest) ProtoMessage()    {}
func (*NewCardTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{16}
}

func (m *NewCardTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCardTokenRequest.Unmarshal(m, b)
}
func (m *NewCardTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCardTokenRequest.Marshal(b, m, deterministic)
}
func (m *NewCardTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCardTokenRequest.Merge(m, src)
}
func (m *NewCardTokenRequest) XXX_Size() int {
	return xxx_messageInfo_NewCardTokenRequest.Size(m)
}
func (m *NewCardTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCardTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewCardTokenRequest proto.InternalMessageInfo

func (m *NewCardTokenRequest) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

func (m *NewCardTokenRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *NewCardTokenRequest) GetType() CardTokenType {
	if m != nil {
		return m.Type
	}
	return CardTokenType_ONEUSE
}

type Card struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	ExpMont              int32    `protobuf:"varint,2,opt,name=expMont,proto3" json:"expMont,omitempty"`
	ExpYear              int32    `protobuf:"varint,3,opt,name=expYear,proto3" json:"expYear,omitempty"`
	Cvc                  string   `protobuf:"bytes,4,opt,name=cvc,proto3" json:"cvc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{17}
}

func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (m *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(m, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Card) GetExpMont() int32 {
	if m != nil {
		return m.ExpMont
	}
	return 0
}

func (m *Card) GetExpYear() int32 {
	if m != nil {
		return m.ExpYear
	}
	return 0
}

func (m *Card) GetCvc() string {
	if m != nil {
		return m.Cvc
	}
	return ""
}

type Customer struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string    `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string    `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Location             *Location `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{18}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Customer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Customer) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Customer) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Location struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{19}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Location) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type CardToken struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 CardTokenType        `protobuf:"varint,2,opt,name=type,proto3,enum=CardTokenType" json:"type,omitempty"`
	Value                string               `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	WithCard             *EncodedCardDetails  `protobuf:"bytes,4,opt,name=withCard,proto3" json:"withCard,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CardToken) Reset()         { *m = CardToken{} }
func (m *CardToken) String() string { return proto.CompactTextString(m) }
func (*CardToken) ProtoMessage()    {}
func (*CardToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{20}
}

func (m *CardToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardToken.Unmarshal(m, b)
}
func (m *CardToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardToken.Marshal(b, m, deterministic)
}
func (m *CardToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardToken.Merge(m, src)
}
func (m *CardToken) XXX_Size() int {
	return xxx_messageInfo_CardToken.Size(m)
}
func (m *CardToken) XXX_DiscardUnknown() {
	xxx_messageInfo_CardToken.DiscardUnknown(m)
}

var xxx_messageInfo_CardToken proto.InternalMessageInfo

func (m *CardToken) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CardToken) GetType() CardTokenType {
	if m != nil {
		return m.Type
	}
	return CardTokenType_ONEUSE
}

func (m *CardToken) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *CardToken) GetWithCard() *EncodedCardDetails {
	if m != nil {
		return m.WithCard
	}
	return nil
}

func (m *CardToken) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type EncodedCardDetails struct {
	Number               string    `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	ExpirationYear       int32     `protobuf:"varint,2,opt,name=expirationYear,proto3" json:"expirationYear,omitempty"`
	Customer             *Customer `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EncodedCardDetails) Reset()         { *m = EncodedCardDetails{} }
func (m *EncodedCardDetails) String() string { return proto.CompactTextString(m) }
func (*EncodedCardDetails) ProtoMessage()    {}
func (*EncodedCardDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{21}
}

func (m *EncodedCardDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncodedCardDetails.Unmarshal(m, b)
}
func (m *EncodedCardDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncodedCardDetails.Marshal(b, m, deterministic)
}
func (m *EncodedCardDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodedCardDetails.Merge(m, src)
}
func (m *EncodedCardDetails) XXX_Size() int {
	return xxx_messageInfo_EncodedCardDetails.Size(m)
}
func (m *EncodedCardDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodedCardDetails.DiscardUnknown(m)
}

var xxx_messageInfo_EncodedCardDetails proto.InternalMessageInfo

func (m *EncodedCardDetails) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *EncodedCardDetails) GetExpirationYear() int32 {
	if m != nil {
		return m.ExpirationYear
	}
	return 0
}

func (m *EncodedCardDetails) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type Sale struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	State                SaleState            `protobuf:"varint,4,opt,name=state,proto3,enum=SaleState" json:"state,omitempty"`
	Customer             *Customer            `protobuf:"bytes,5,opt,name=customer,proto3" json:"customer,omitempty"`
	Products             []*Product           `protobuf:"bytes,6,rep,name=products,proto3" json:"products,omitempty"`
	DiscountCodes        []*DiscountCode      `protobuf:"bytes,7,rep,name=discountCodes,proto3" json:"discountCodes,omitempty"`
	CardToken            *CardToken           `protobuf:"bytes,8,opt,name=cardToken,proto3" json:"cardToken,omitempty"`
	Charge               *ChargeToken         `protobuf:"bytes,9,opt,name=charge,proto3" json:"charge,omitempty"`
	CurrencyToPay        string               `protobuf:"bytes,10,opt,name=currencyToPay,proto3" json:"currencyToPay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Sale) Reset()         { *m = Sale{} }
func (m *Sale) String() string { return proto.CompactTextString(m) }
func (*Sale) ProtoMessage()    {}
func (*Sale) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{22}
}

func (m *Sale) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sale.Unmarshal(m, b)
}
func (m *Sale) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sale.Marshal(b, m, deterministic)
}
func (m *Sale) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sale.Merge(m, src)
}
func (m *Sale) XXX_Size() int {
	return xxx_messageInfo_Sale.Size(m)
}
func (m *Sale) XXX_DiscardUnknown() {
	xxx_messageInfo_Sale.DiscardUnknown(m)
}

var xxx_messageInfo_Sale proto.InternalMessageInfo

func (m *Sale) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Sale) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Sale) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Sale) GetState() SaleState {
	if m != nil {
		return m.State
	}
	return SaleState_NULL
}

func (m *Sale) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *Sale) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Sale) GetDiscountCodes() []*DiscountCode {
	if m != nil {
		return m.DiscountCodes
	}
	return nil
}

func (m *Sale) GetCardToken() *CardToken {
	if m != nil {
		return m.CardToken
	}
	return nil
}

func (m *Sale) GetCharge() *ChargeToken {
	if m != nil {
		return m.Charge
	}
	return nil
}

func (m *Sale) GetCurrencyToPay() string {
	if m != nil {
		return m.CurrencyToPay
	}
	return ""
}

type Product struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Details              string   `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	Cost                 *Cost    `protobuf:"bytes,3,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{23}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Product) GetCost() *Cost {
	if m != nil {
		return m.Cost
	}
	return nil
}

type Cost struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cost) Reset()         { *m = Cost{} }
func (m *Cost) String() string { return proto.CompactTextString(m) }
func (*Cost) ProtoMessage()    {}
func (*Cost) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{24}
}

func (m *Cost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cost.Unmarshal(m, b)
}
func (m *Cost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cost.Marshal(b, m, deterministic)
}
func (m *Cost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cost.Merge(m, src)
}
func (m *Cost) XXX_Size() int {
	return xxx_messageInfo_Cost.Size(m)
}
func (m *Cost) XXX_DiscardUnknown() {
	xxx_messageInfo_Cost.DiscardUnknown(m)
}

var xxx_messageInfo_Cost proto.InternalMessageInfo

func (m *Cost) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Cost) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type ChargeToken struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                string               `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	WithCardToken        *CardToken           `protobuf:"bytes,4,opt,name=withCardToken,proto3" json:"withCardToken,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChargeToken) Reset()         { *m = ChargeToken{} }
func (m *ChargeToken) String() string { return proto.CompactTextString(m) }
func (*ChargeToken) ProtoMessage()    {}
func (*ChargeToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{25}
}

func (m *ChargeToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeToken.Unmarshal(m, b)
}
func (m *ChargeToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeToken.Marshal(b, m, deterministic)
}
func (m *ChargeToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeToken.Merge(m, src)
}
func (m *ChargeToken) XXX_Size() int {
	return xxx_messageInfo_ChargeToken.Size(m)
}
func (m *ChargeToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeToken.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeToken proto.InternalMessageInfo

func (m *ChargeToken) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChargeToken) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ChargeToken) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChargeToken) GetWithCardToken() *CardToken {
	if m != nil {
		return m.WithCardToken
	}
	return nil
}

func (m *ChargeToken) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type DiscountCode struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	MaxUses              int32                `protobuf:"varint,4,opt,name=maxUses,proto3" json:"maxUses,omitempty"`
	Uses                 []*DiscountUseRecord `protobuf:"bytes,5,rep,name=uses,proto3" json:"uses,omitempty"`
	Code                 string               `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Value                *Discount            `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DiscountCode) Reset()         { *m = DiscountCode{} }
func (m *DiscountCode) String() string { return proto.CompactTextString(m) }
func (*DiscountCode) ProtoMessage()    {}
func (*DiscountCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{26}
}

func (m *DiscountCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountCode.Unmarshal(m, b)
}
func (m *DiscountCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountCode.Marshal(b, m, deterministic)
}
func (m *DiscountCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountCode.Merge(m, src)
}
func (m *DiscountCode) XXX_Size() int {
	return xxx_messageInfo_DiscountCode.Size(m)
}
func (m *DiscountCode) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountCode.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountCode proto.InternalMessageInfo

func (m *DiscountCode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DiscountCode) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *DiscountCode) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *DiscountCode) GetMaxUses() int32 {
	if m != nil {
		return m.MaxUses
	}
	return 0
}

func (m *DiscountCode) GetUses() []*DiscountUseRecord {
	if m != nil {
		return m.Uses
	}
	return nil
}

func (m *DiscountCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DiscountCode) GetValue() *Discount {
	if m != nil {
		return m.Value
	}
	return nil
}

type DiscountUseRecord struct {
	At                   *timestamp.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	By                   *Customer            `protobuf:"bytes,2,opt,name=by,proto3" json:"by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DiscountUseRecord) Reset()         { *m = DiscountUseRecord{} }
func (m *DiscountUseRecord) String() string { return proto.CompactTextString(m) }
func (*DiscountUseRecord) ProtoMessage()    {}
func (*DiscountUseRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{27}
}

func (m *DiscountUseRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountUseRecord.Unmarshal(m, b)
}
func (m *DiscountUseRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountUseRecord.Marshal(b, m, deterministic)
}
func (m *DiscountUseRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountUseRecord.Merge(m, src)
}
func (m *DiscountUseRecord) XXX_Size() int {
	return xxx_messageInfo_DiscountUseRecord.Size(m)
}
func (m *DiscountUseRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountUseRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountUseRecord proto.InternalMessageInfo

func (m *DiscountUseRecord) GetAt() *timestamp.Timestamp {
	if m != nil {
		return m.At
	}
	return nil
}

func (m *DiscountUseRecord) GetBy() *Customer {
	if m != nil {
		return m.By
	}
	return nil
}

type Discount struct {
	Type                 DiscountType `protobuf:"varint,1,opt,name=type,proto3,enum=DiscountType" json:"type,omitempty"`
	Percent              float64      `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent,omitempty"`
	Amount               float64      `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string       `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Discount) Reset()         { *m = Discount{} }
func (m *Discount) String() string { return proto.CompactTextString(m) }
func (*Discount) ProtoMessage()    {}
func (*Discount) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{28}
}

func (m *Discount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discount.Unmarshal(m, b)
}
func (m *Discount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discount.Marshal(b, m, deterministic)
}
func (m *Discount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discount.Merge(m, src)
}
func (m *Discount) XXX_Size() int {
	return xxx_messageInfo_Discount.Size(m)
}
func (m *Discount) XXX_DiscardUnknown() {
	xxx_messageInfo_Discount.DiscardUnknown(m)
}

var xxx_messageInfo_Discount proto.InternalMessageInfo

func (m *Discount) GetType() DiscountType {
	if m != nil {
		return m.Type
	}
	return DiscountType_STATIC
}

func (m *Discount) GetPercent() float64 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *Discount) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Discount) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func init() {
	proto.RegisterEnum("CardTokenType", CardTokenType_name, CardTokenType_value)
	proto.RegisterEnum("SaleState", SaleState_name, SaleState_value)
	proto.RegisterEnum("DiscountType", DiscountType_name, DiscountType_value)
	proto.RegisterType((*DiscountCodeValue)(nil), "DiscountCodeValue")
	proto.RegisterType((*DiscountCodeExist)(nil), "DiscountCodeExist")
	proto.RegisterType((*ChargeWithNativeToken)(nil), "ChargeWithNativeToken")
	proto.RegisterType((*DiscountCodes)(nil), "DiscountCodes")
	proto.RegisterType((*ActiveDiscountsRequest)(nil), "ActiveDiscountsRequest")
	proto.RegisterType((*DiscountCodeID)(nil), "DiscountCodeID")
	proto.RegisterType((*DiscountCodeRequest)(nil), "DiscountCodeRequest")
	proto.RegisterType((*SaleUpdateRequest)(nil), "SaleUpdateRequest")
	proto.RegisterType((*DeliverSaleRequest)(nil), "DeliverSaleRequest")
	proto.RegisterType((*DeliverChannelResponse)(nil), "DeliverChannelResponse")
	proto.RegisterType((*DeliveryChannel)(nil), "DeliveryChannel")
	proto.RegisterType((*SaleIDRequest)(nil), "SaleIDRequest")
	proto.RegisterType((*FastSale)(nil), "FastSale")
	proto.RegisterType((*NewSaleRequest)(nil), "NewSaleRequest")
	proto.RegisterType((*CardTokenByID)(nil), "CardTokenByID")
	proto.RegisterType((*CardTokenByCustomer)(nil), "CardTokenByCustomer")
	proto.RegisterType((*NewCardTokenRequest)(nil), "NewCardTokenRequest")
	proto.RegisterType((*Card)(nil), "Card")
	proto.RegisterType((*Customer)(nil), "Customer")
	proto.RegisterType((*Location)(nil), "Location")
	proto.RegisterType((*CardToken)(nil), "CardToken")
	proto.RegisterType((*EncodedCardDetails)(nil), "EncodedCardDetails")
	proto.RegisterType((*Sale)(nil), "Sale")
	proto.RegisterType((*Product)(nil), "Product")
	proto.RegisterType((*Cost)(nil), "Cost")
	proto.RegisterType((*ChargeToken)(nil), "ChargeToken")
	proto.RegisterType((*DiscountCode)(nil), "DiscountCode")
	proto.RegisterType((*DiscountUseRecord)(nil), "DiscountUseRecord")
	proto.RegisterType((*Discount)(nil), "Discount")
}

func init() { proto.RegisterFile("proto/plutus.proto", fileDescriptor_43f31399d60808ca) }

var fileDescriptor_43f31399d60808ca = []byte{
	// 1525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x5b, 0x6f, 0xdb, 0x46,
	0x16, 0xb6, 0x24, 0xea, 0x76, 0x14, 0xc9, 0xca, 0xd8, 0x71, 0x14, 0x3d, 0xac, 0x1d, 0x6e, 0x6e,
	0xf0, 0xee, 0x8e, 0xbd, 0x0e, 0x16, 0xc8, 0x2e, 0x82, 0x05, 0x1c, 0x49, 0x71, 0x14, 0x64, 0x65,
	0xef, 0x58, 0x4e, 0xd1, 0x02, 0x05, 0x3a, 0x26, 0x27, 0x36, 0x11, 0x89, 0x64, 0xc9, 0x91, 0x6d,
	0x25, 0x4f, 0xfd, 0x2f, 0xfd, 0x13, 0x7d, 0xeb, 0x9f, 0xea, 0x4b, 0x9f, 0x8a, 0xb9, 0x51, 0xa4,
	0x2e, 0xa9, 0x8b, 0xbe, 0xf1, 0xdc, 0x79, 0xce, 0x7c, 0xe7, 0xcc, 0x19, 0x40, 0x61, 0x14, 0xf0,
	0x60, 0x2f, 0x1c, 0x4d, 0xf8, 0x24, 0xc6, 0x92, 0x68, 0x6f, 0x5f, 0x04, 0xc1, 0xc5, 0x88, 0xed,
	0x49, 0xea, 0x7c, 0xf2, 0x61, 0x8f, 0x7b, 0x63, 0x16, 0x73, 0x3a, 0x0e, 0x95, 0x82, 0xdd, 0x87,
	0xbb, 0x5d, 0x2f, 0x76, 0x82, 0x89, 0xcf, 0x3b, 0x81, 0xcb, 0xde, 0xd3, 0xd1, 0x84, 0xa1, 0x4d,
	0x28, 0x5e, 0x89, 0x8f, 0x56, 0x6e, 0x27, 0xf7, 0xac, 0x4a, 0x14, 0x81, 0xfe, 0x02, 0xe0, 0x4c,
	0x62, 0x1e, 0x8c, 0x59, 0xd4, 0xef, 0xb6, 0xf2, 0x52, 0x94, 0xe2, 0xd8, 0x7f, 0xcd, 0xba, 0xea,
	0xdd, 0x78, 0x31, 0x47, 0x0d, 0xc8, 0x07, 0x1f, 0xa5, 0x9f, 0x0a, 0xc9, 0x07, 0x1f, 0xed, 0xff,
	0xc3, 0xbd, 0xce, 0x25, 0x8d, 0x2e, 0xd8, 0x57, 0x1e, 0xbf, 0x1c, 0x50, 0xee, 0x5d, 0xb1, 0x61,
	0xf0, 0x91, 0xf9, 0x68, 0x0b, 0x4a, 0x31, 0x1d, 0xb1, 0x7e, 0x57, 0x07, 0xd5, 0x14, 0xda, 0x81,
	0x9a, 0x3f, 0x53, 0xd3, 0x61, 0xd3, 0x2c, 0xfb, 0x25, 0xd4, 0xd3, 0x71, 0x63, 0xf4, 0x37, 0xa8,
	0xba, 0x9a, 0x11, 0xb7, 0x72, 0x3b, 0x85, 0x67, 0xb5, 0x83, 0x3a, 0x4e, 0xab, 0x90, 0x99, 0xdc,
	0x7e, 0x0b, 0x5b, 0x87, 0x8e, 0x70, 0x66, 0x14, 0x62, 0xc2, 0xbe, 0x9f, 0xb0, 0x98, 0xa3, 0x7d,
	0x28, 0x4e, 0x7c, 0xee, 0x8d, 0xe4, 0x0f, 0xd5, 0x0e, 0xda, 0x58, 0xd5, 0x12, 0x9b, 0x5a, 0xe2,
	0xa1, 0xa9, 0x25, 0x51, 0x8a, 0xf6, 0x0e, 0x34, 0xd2, 0x61, 0xfa, 0x5d, 0x91, 0xbe, 0xe7, 0xea,
	0x8c, 0xf2, 0x9e, 0x6b, 0xdf, 0x83, 0x8d, 0xcc, 0x8f, 0xa8, 0x50, 0xf6, 0x5b, 0xb8, 0x7b, 0x4a,
	0x47, 0xec, 0x2c, 0x74, 0x29, 0x37, 0xcc, 0x79, 0x5b, 0xf4, 0x18, 0x60, 0x22, 0x15, 0xba, 0x94,
	0x53, 0x59, 0x88, 0xda, 0x41, 0x11, 0x0b, 0x3b, 0x92, 0x12, 0xd8, 0x2e, 0xa0, 0x2e, 0x1b, 0x79,
	0x57, 0x2c, 0x92, 0x22, 0xed, 0xcc, 0x06, 0x4b, 0x14, 0x54, 0xe7, 0xd2, 0x90, 0x66, 0xfd, 0xae,
	0x96, 0x12, 0x29, 0x43, 0xbb, 0x50, 0x76, 0x2e, 0xa9, 0xef, 0xb3, 0x91, 0xf6, 0xde, 0xc4, 0xda,
	0xd3, 0xb4, 0xa3, 0xf8, 0xc4, 0x28, 0xd8, 0xaf, 0x61, 0x4b, 0xcb, 0x8c, 0x88, 0xc5, 0x61, 0xe0,
	0xc7, 0x0c, 0xb5, 0xa0, 0x3c, 0x66, 0x71, 0x4c, 0x2f, 0x0c, 0x7c, 0x0c, 0x89, 0x10, 0x58, 0x4e,
	0xe0, 0x32, 0x7d, 0x86, 0xf2, 0xdb, 0xa6, 0xb0, 0x3e, 0x17, 0x03, 0x35, 0x67, 0x79, 0xbf, 0x59,
	0x93, 0x99, 0x6f, 0x82, 0xe5, 0xd3, 0xb1, 0x36, 0x7c, 0xb3, 0x46, 0x24, 0x25, 0xb8, 0xd2, 0x5d,
	0xc1, 0x70, 0x05, 0xf5, 0xaa, 0x09, 0x0d, 0xcf, 0x65, 0x3e, 0xf7, 0x3e, 0x78, 0x0e, 0xe5, 0x5e,
	0xe0, 0xdb, 0xdb, 0x50, 0xcf, 0x64, 0xbb, 0x70, 0x28, 0xef, 0xa1, 0xf2, 0x9a, 0xc6, 0x5c, 0x28,
	0xa1, 0x47, 0x50, 0x37, 0x90, 0xee, 0x8d, 0xa9, 0x3e, 0xfc, 0x2a, 0xc9, 0x32, 0xd1, 0x23, 0xa8,
	0x84, 0x51, 0xe0, 0x4e, 0x1c, 0x1e, 0xb7, 0xf2, 0x12, 0x60, 0x15, 0x7c, 0xa2, 0x18, 0x24, 0x91,
	0xd8, 0xdf, 0x42, 0x63, 0xc0, 0xae, 0xd3, 0xa7, 0xf0, 0x18, 0x2a, 0xc6, 0x91, 0x3e, 0x89, 0x2a,
	0xee, 0x68, 0x06, 0x49, 0x44, 0xb7, 0x74, 0xbf, 0x0d, 0xf5, 0x0e, 0x8d, 0x5c, 0xd9, 0x04, 0xaf,
	0xa6, 0x4b, 0xc0, 0xf6, 0x12, 0x36, 0x52, 0x0a, 0x26, 0xce, 0x2d, 0x7f, 0xc2, 0xfe, 0x0c, 0x1b,
	0x03, 0x76, 0x9d, 0x38, 0x30, 0x29, 0x3c, 0x00, 0xcb, 0xa1, 0x91, 0xab, 0x2d, 0x8b, 0x58, 0x28,
	0x10, 0xc9, 0xca, 0x38, 0xce, 0xaf, 0xce, 0xce, 0x06, 0x8b, 0x4f, 0x43, 0x75, 0x6e, 0x8d, 0x83,
	0x06, 0x4e, 0x42, 0x0c, 0xa7, 0x21, 0x23, 0x52, 0x66, 0xbb, 0x60, 0x09, 0xb6, 0x98, 0x0a, 0xfe,
	0x64, 0x7c, 0xae, 0xff, 0xb4, 0x4a, 0x34, 0x25, 0x40, 0xc6, 0x6e, 0xc2, 0xff, 0x05, 0x3e, 0x97,
	0x91, 0x8a, 0xc4, 0x90, 0x5a, 0xf2, 0x35, 0xa3, 0x91, 0x0c, 0xa0, 0x24, 0x82, 0x44, 0x4d, 0x28,
	0x38, 0x57, 0x4e, 0xcb, 0x92, 0x8e, 0xc4, 0xa7, 0xfd, 0x43, 0x0e, 0x2a, 0x49, 0x59, 0xe6, 0xdb,
	0x6d, 0x13, 0x8a, 0x4c, 0x22, 0x40, 0xc1, 0x55, 0x11, 0x02, 0xc3, 0x12, 0x8a, 0x05, 0x85, 0x61,
	0x0d, 0xc4, 0x62, 0x78, 0x19, 0xf8, 0x4c, 0xbb, 0x56, 0x84, 0xa8, 0xc6, 0x28, 0x50, 0x10, 0x6c,
	0x15, 0x75, 0x35, 0xde, 0x69, 0x06, 0x49, 0x44, 0xf6, 0x77, 0x50, 0x31, 0x5c, 0xf1, 0xef, 0xd4,
	0x75, 0x23, 0x16, 0xc7, 0xa6, 0x75, 0x34, 0x29, 0x5b, 0xc7, 0xe3, 0xd3, 0xa4, 0x75, 0x3c, 0x3e,
	0x15, 0x61, 0x63, 0x4e, 0xb9, 0xf9, 0x17, 0x45, 0x88, 0x2c, 0x3f, 0x79, 0xa1, 0xc9, 0xf2, 0x93,
	0x17, 0xda, 0x3f, 0xe7, 0xa0, 0x9a, 0xd4, 0x78, 0x21, 0x4d, 0x73, 0x1a, 0xf9, 0xd5, 0xa7, 0x31,
	0xbb, 0x0f, 0x0a, 0xe9, 0xfb, 0x60, 0x0f, 0x2a, 0xd7, 0x1e, 0xbf, 0x14, 0x06, 0x32, 0x5c, 0xed,
	0x60, 0x03, 0xf7, 0x7c, 0xd1, 0x84, 0xae, 0xe0, 0x75, 0x19, 0xa7, 0xde, 0x28, 0x26, 0x89, 0x12,
	0x7a, 0x01, 0x55, 0x27, 0x62, 0x94, 0x33, 0xf7, 0x90, 0xeb, 0x92, 0x7c, 0x69, 0xa8, 0xce, 0x94,
	0xed, 0xcf, 0x80, 0x16, 0x3d, 0xaf, 0x04, 0xc7, 0x13, 0x68, 0xb0, 0x9b, 0xd0, 0x8b, 0x64, 0x51,
	0x25, 0x12, 0x14, 0x46, 0xe6, 0xb8, 0x19, 0xbc, 0x16, 0x56, 0x37, 0xc2, 0x8f, 0x05, 0xb0, 0xe4,
	0x6c, 0x98, 0x2f, 0x5d, 0x26, 0x9f, 0xfc, 0x1f, 0xc8, 0x47, 0x58, 0xaa, 0x89, 0x2d, 0x2c, 0x0b,
	0xbf, 0x6f, 0x99, 0x28, 0xa3, 0x1d, 0x73, 0xe8, 0x96, 0x3c, 0x2f, 0x90, 0x83, 0xfc, 0x54, 0x70,
	0x0c, 0x00, 0xd2, 0x59, 0x15, 0x6f, 0x37, 0x63, 0x4a, 0xab, 0x66, 0x0c, 0x7a, 0x0e, 0x75, 0x37,
	0x7d, 0xb7, 0xb6, 0xca, 0xcb, 0xae, 0xd3, 0xac, 0x0e, 0x7a, 0x06, 0x55, 0xc7, 0xa0, 0xa8, 0x55,
	0x91, 0xbf, 0x00, 0x33, 0x5c, 0x91, 0x99, 0x10, 0x3d, 0x82, 0x92, 0x23, 0xb7, 0x81, 0x56, 0x55,
	0xaa, 0xdd, 0xc1, 0x6a, 0x39, 0x50, 0x8a, 0x5a, 0xa6, 0x66, 0x72, 0x14, 0x31, 0xdf, 0x99, 0x0e,
	0x83, 0x13, 0x3a, 0x6d, 0x81, 0x99, 0xc9, 0x29, 0xa6, 0x4d, 0xa0, 0xac, 0xff, 0x3f, 0x69, 0xd2,
	0x5c, 0xaa, 0x49, 0x5b, 0x50, 0x76, 0x15, 0x6e, 0x74, 0x13, 0x19, 0x52, 0x4e, 0xb4, 0x20, 0x36,
	0xe7, 0x50, 0xc4, 0x9d, 0x40, 0xdc, 0x88, 0x82, 0x65, 0xff, 0x07, 0x2c, 0x41, 0x09, 0xa4, 0xd1,
	0xb1, 0x48, 0x50, 0xba, 0xcc, 0x11, 0x4d, 0xa1, 0xb6, 0xa8, 0xb5, 0xfa, 0x09, 0xed, 0x35, 0xa1,
	0xed, 0x9f, 0x72, 0x50, 0x4b, 0x65, 0xb3, 0x6c, 0xbe, 0xa8, 0xa6, 0xca, 0xa7, 0x9b, 0x2a, 0x75,
	0x7b, 0x16, 0xb2, 0xb7, 0xe7, 0x3e, 0xd4, 0x4d, 0x27, 0xa9, 0xca, 0x5a, 0x0b, 0x95, 0xcd, 0x2a,
	0xfc, 0x89, 0x7e, 0xfb, 0x25, 0x07, 0x77, 0xd2, 0x27, 0xbc, 0xf0, 0xf3, 0xfb, 0x12, 0x86, 0xd1,
	0x6d, 0x60, 0xaf, 0x14, 0xd1, 0xdf, 0xa1, 0xc0, 0x7c, 0xf7, 0x16, 0x60, 0x17, 0x6a, 0xb2, 0x0c,
	0xf4, 0xe6, 0x2c, 0x66, 0xb1, 0x4c, 0xb3, 0x48, 0x0c, 0x89, 0x9e, 0x80, 0x35, 0x11, 0xec, 0xa2,
	0x04, 0x22, 0x4a, 0x80, 0x78, 0x16, 0x33, 0xc2, 0x9c, 0x40, 0x5c, 0x46, 0x42, 0x9e, 0x2c, 0x1b,
	0xa5, 0xd9, 0xb2, 0x81, 0xb6, 0x4d, 0xc9, 0xcb, 0xba, 0x2f, 0x8c, 0xb1, 0xae, 0xbe, 0xfd, 0xcd,
	0x6c, 0x85, 0x4d, 0xfc, 0xa1, 0x5d, 0xc8, 0x53, 0x7e, 0x8b, 0x25, 0x30, 0x4f, 0xc5, 0xed, 0x98,
	0x3f, 0x9f, 0x2e, 0x5e, 0x7e, 0xf9, 0xf3, 0xa9, 0xfd, 0x19, 0x2a, 0xc6, 0x37, 0x7a, 0xa8, 0x87,
	0x6e, 0x4e, 0x36, 0xf1, 0xac, 0x9b, 0x52, 0x33, 0xb7, 0x05, 0xe5, 0x90, 0x45, 0x0e, 0xd3, 0x37,
	0x5c, 0x8e, 0x18, 0x32, 0x05, 0xc6, 0xc2, 0x4a, 0x30, 0x5a, 0x59, 0x30, 0xee, 0xee, 0xa6, 0x76,
	0x05, 0x11, 0x04, 0x01, 0x94, 0x8e, 0x07, 0xbd, 0xb3, 0xd3, 0x5e, 0x73, 0x0d, 0xd5, 0xa1, 0x4a,
	0x7a, 0x9d, 0x33, 0x42, 0x7a, 0x83, 0x61, 0x33, 0xb7, 0xdb, 0x81, 0x6a, 0x32, 0x54, 0x50, 0x05,
	0xac, 0xc1, 0xd9, 0xbb, 0x77, 0xcd, 0x35, 0x54, 0x85, 0x62, 0x97, 0x1c, 0xbe, 0x1e, 0x36, 0x73,
	0xc2, 0xf8, 0xb4, 0x7f, 0x34, 0xe8, 0x75, 0x9b, 0x79, 0x54, 0x83, 0xf2, 0xc9, 0x61, 0xbf, 0x7b,
	0x7c, 0x36, 0x6c, 0x16, 0x84, 0x76, 0xf7, 0x78, 0xd0, 0x6b, 0x5a, 0xbb, 0x4f, 0x67, 0x00, 0x32,
	0xf1, 0x4e, 0x87, 0x87, 0xc3, 0x7e, 0xa7, 0xb9, 0x26, 0x4d, 0x7a, 0xa4, 0x23, 0xa3, 0x1d, 0xfc,
	0x5a, 0x82, 0xd2, 0x89, 0x7c, 0xb2, 0xa0, 0x7d, 0xb8, 0x93, 0xde, 0x38, 0xd0, 0x26, 0x5e, 0xb2,
	0x80, 0xb4, 0x53, 0x80, 0x47, 0x2f, 0xa0, 0x7d, 0xc4, 0x78, 0x42, 0x1f, 0x7f, 0x30, 0x15, 0x57,
	0xfb, 0x10, 0xce, 0xec, 0x47, 0x19, 0xcb, 0x2e, 0xec, 0xac, 0xb2, 0x4c, 0x36, 0x82, 0x4d, 0xbc,
	0x64, 0x7d, 0xca, 0x78, 0xf9, 0x87, 0xdc, 0x5e, 0x19, 0x67, 0xa9, 0xfb, 0xf5, 0x0b, 0x41, 0xb7,
	0xa1, 0x36, 0x60, 0xd7, 0xc9, 0xae, 0x59, 0xc5, 0xe6, 0xb3, 0xad, 0xf6, 0x78, 0xf4, 0x10, 0xca,
	0x7a, 0x63, 0x44, 0xeb, 0x38, 0xbb, 0x3b, 0x1a, 0x95, 0x1d, 0x28, 0x1f, 0x31, 0x65, 0x3f, 0xb7,
	0xc5, 0x1b, 0x8d, 0xa7, 0x00, 0xea, 0x21, 0x21, 0x29, 0x84, 0x17, 0x5e, 0x16, 0x46, 0xf1, 0xd5,
	0xdc, 0x4b, 0xc1, 0x61, 0x5e, 0xc8, 0xd1, 0x06, 0x5e, 0x7c, 0x3e, 0xb4, 0xef, 0xe3, 0x15, 0xdb,
	0x3e, 0x86, 0x86, 0x1a, 0x72, 0x42, 0x5b, 0x57, 0x3d, 0xfb, 0x57, 0x99, 0x99, 0x8e, 0x0e, 0xe1,
	0xc1, 0x4c, 0x7f, 0xe1, 0x0d, 0x88, 0x97, 0xbe, 0x0d, 0xe7, 0x5c, 0x3c, 0x84, 0x4a, 0x37, 0xf0,
	0xd9, 0x97, 0x4a, 0xf0, 0x6f, 0x40, 0x1d, 0x39, 0xcc, 0x32, 0x43, 0x6c, 0x13, 0x2f, 0x79, 0x7b,
	0xb5, 0xb3, 0x77, 0x19, 0xfa, 0x27, 0xac, 0x1f, 0x31, 0x9e, 0x61, 0xad, 0xe3, 0xec, 0xab, 0x6e,
	0xde, 0xe4, 0xbf, 0xb0, 0xf9, 0x9e, 0x8e, 0x3c, 0x77, 0x3e, 0x1e, 0xc2, 0x0b, 0x4f, 0xeb, 0x76,
	0x96, 0xa7, 0xde, 0xc8, 0x87, 0xb0, 0x75, 0xc4, 0x78, 0xf6, 0x15, 0xaa, 0x6e, 0xd2, 0xfb, 0x78,
	0xf9, 0xdb, 0xb4, 0xdd, 0xc0, 0x59, 0xc5, 0x7f, 0xc9, 0xa3, 0x64, 0x73, 0x3f, 0xb0, 0xf0, 0xe3,
	0x73, 0x66, 0xe7, 0x25, 0x39, 0xc6, 0x9e, 0xff, 0x16, 0x00, 0x00, 0xff, 0xff, 0x16, 0xbe, 0x34,
	0x4a, 0x3b, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlutusClient is the client API for Plutus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlutusClient interface {
	NewCardToken(ctx context.Context, in *NewCardTokenRequest, opts ...grpc.CallOption) (*CardToken, error)
	GetCardTokenOfCustomerByID(ctx context.Context, in *CardTokenByID, opts ...grpc.CallOption) (*CardToken, error)
	GetCardTokenOfCustomerByCustomer(ctx context.Context, in *CardTokenByCustomer, opts ...grpc.CallOption) (*CardToken, error)
	DeleteCardToken(ctx context.Context, in *CardTokenByID, opts ...grpc.CallOption) (*CardToken, error)
	NewFastSale(ctx context.Context, in *FastSale, opts ...grpc.CallOption) (*Sale, error)
	NewSale(ctx context.Context, in *NewSaleRequest, opts ...grpc.CallOption) (*Sale, error)
	GetSale(ctx context.Context, in *SaleIDRequest, opts ...grpc.CallOption) (*Sale, error)
	UpdateSale(ctx context.Context, in *SaleUpdateRequest, opts ...grpc.CallOption) (*Sale, error)
	DeliverSaleReceipt(ctx context.Context, in *DeliverSaleRequest, opts ...grpc.CallOption) (*DeliverChannelResponse, error)
	ChargeSaleByID(ctx context.Context, in *SaleIDRequest, opts ...grpc.CallOption) (*ChargeToken, error)
	ChargeSaleWithNativeToken(ctx context.Context, in *ChargeWithNativeToken, opts ...grpc.CallOption) (*ChargeToken, error)
	DoneSale(ctx context.Context, in *SaleIDRequest, opts ...grpc.CallOption) (*Sale, error)
	CreateDiscountCode(ctx context.Context, in *DiscountCodeRequest, opts ...grpc.CallOption) (*DiscountCode, error)
	GetDiscountCode(ctx context.Context, in *DiscountCodeID, opts ...grpc.CallOption) (*DiscountCode, error)
	ValidateDiscountCode(ctx context.Context, in *DiscountCodeValue, opts ...grpc.CallOption) (*DiscountCodeExist, error)
	GetActiveDiscountCodes(ctx context.Context, in *ActiveDiscountsRequest, opts ...grpc.CallOption) (*DiscountCodes, error)
	DeleteDiscountCode(ctx context.Context, in *DiscountCodeID, opts ...grpc.CallOption) (*DiscountCodes, error)
}

type plutusClient struct {
	cc *grpc.ClientConn
}

func NewPlutusClient(cc *grpc.ClientConn) PlutusClient {
	return &plutusClient{cc}
}

func (c *plutusClient) NewCardToken(ctx context.Context, in *NewCardTokenRequest, opts ...grpc.CallOption) (*CardToken, error) {
	out := new(CardToken)
	err := c.cc.Invoke(ctx, "/Plutus/NewCardToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) GetCardTokenOfCustomerByID(ctx context.Context, in *CardTokenByID, opts ...grpc.CallOption) (*CardToken, error) {
	out := new(CardToken)
	err := c.cc.Invoke(ctx, "/Plutus/GetCardTokenOfCustomerByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) GetCardTokenOfCustomerByCustomer(ctx context.Context, in *CardTokenByCustomer, opts ...grpc.CallOption) (*CardToken, error) {
	out := new(CardToken)
	err := c.cc.Invoke(ctx, "/Plutus/GetCardTokenOfCustomerByCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) DeleteCardToken(ctx context.Context, in *CardTokenByID, opts ...grpc.CallOption) (*CardToken, error) {
	out := new(CardToken)
	err := c.cc.Invoke(ctx, "/Plutus/DeleteCardToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) NewFastSale(ctx context.Context, in *FastSale, opts ...grpc.CallOption) (*Sale, error) {
	out := new(Sale)
	err := c.cc.Invoke(ctx, "/Plutus/NewFastSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) NewSale(ctx context.Context, in *NewSaleRequest, opts ...grpc.CallOption) (*Sale, error) {
	out := new(Sale)
	err := c.cc.Invoke(ctx, "/Plutus/NewSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) GetSale(ctx context.Context, in *SaleIDRequest, opts ...grpc.CallOption) (*Sale, error) {
	out := new(Sale)
	err := c.cc.Invoke(ctx, "/Plutus/GetSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) UpdateSale(ctx context.Context, in *SaleUpdateRequest, opts ...grpc.CallOption) (*Sale, error) {
	out := new(Sale)
	err := c.cc.Invoke(ctx, "/Plutus/UpdateSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) DeliverSaleReceipt(ctx context.Context, in *DeliverSaleRequest, opts ...grpc.CallOption) (*DeliverChannelResponse, error) {
	out := new(DeliverChannelResponse)
	err := c.cc.Invoke(ctx, "/Plutus/DeliverSaleReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) ChargeSaleByID(ctx context.Context, in *SaleIDRequest, opts ...grpc.CallOption) (*ChargeToken, error) {
	out := new(ChargeToken)
	err := c.cc.Invoke(ctx, "/Plutus/ChargeSaleByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) ChargeSaleWithNativeToken(ctx context.Context, in *ChargeWithNativeToken, opts ...grpc.CallOption) (*ChargeToken, error) {
	out := new(ChargeToken)
	err := c.cc.Invoke(ctx, "/Plutus/ChargeSaleWithNativeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) DoneSale(ctx context.Context, in *SaleIDRequest, opts ...grpc.CallOption) (*Sale, error) {
	out := new(Sale)
	err := c.cc.Invoke(ctx, "/Plutus/DoneSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) CreateDiscountCode(ctx context.Context, in *DiscountCodeRequest, opts ...grpc.CallOption) (*DiscountCode, error) {
	out := new(DiscountCode)
	err := c.cc.Invoke(ctx, "/Plutus/CreateDiscountCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) GetDiscountCode(ctx context.Context, in *DiscountCodeID, opts ...grpc.CallOption) (*DiscountCode, error) {
	out := new(DiscountCode)
	err := c.cc.Invoke(ctx, "/Plutus/GetDiscountCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) ValidateDiscountCode(ctx context.Context, in *DiscountCodeValue, opts ...grpc.CallOption) (*DiscountCodeExist, error) {
	out := new(DiscountCodeExist)
	err := c.cc.Invoke(ctx, "/Plutus/ValidateDiscountCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) GetActiveDiscountCodes(ctx context.Context, in *ActiveDiscountsRequest, opts ...grpc.CallOption) (*DiscountCodes, error) {
	out := new(DiscountCodes)
	err := c.cc.Invoke(ctx, "/Plutus/GetActiveDiscountCodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) DeleteDiscountCode(ctx context.Context, in *DiscountCodeID, opts ...grpc.CallOption) (*DiscountCodes, error) {
	out := new(DiscountCodes)
	err := c.cc.Invoke(ctx, "/Plutus/DeleteDiscountCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlutusServer is the server API for Plutus service.
type PlutusServer interface {
	NewCardToken(context.Context, *NewCardTokenRequest) (*CardToken, error)
	GetCardTokenOfCustomerByID(context.Context, *CardTokenByID) (*CardToken, error)
	GetCardTokenOfCustomerByCustomer(context.Context, *CardTokenByCustomer) (*CardToken, error)
	DeleteCardToken(context.Context, *CardTokenByID) (*CardToken, error)
	NewFastSale(context.Context, *FastSale) (*Sale, error)
	NewSale(context.Context, *NewSaleRequest) (*Sale, error)
	GetSale(context.Context, *SaleIDRequest) (*Sale, error)
	UpdateSale(context.Context, *SaleUpdateRequest) (*Sale, error)
	DeliverSaleReceipt(context.Context, *DeliverSaleRequest) (*DeliverChannelResponse, error)
	ChargeSaleByID(context.Context, *SaleIDRequest) (*ChargeToken, error)
	ChargeSaleWithNativeToken(context.Context, *ChargeWithNativeToken) (*ChargeToken, error)
	DoneSale(context.Context, *SaleIDRequest) (*Sale, error)
	CreateDiscountCode(context.Context, *DiscountCodeRequest) (*DiscountCode, error)
	GetDiscountCode(context.Context, *DiscountCodeID) (*DiscountCode, error)
	ValidateDiscountCode(context.Context, *DiscountCodeValue) (*DiscountCodeExist, error)
	GetActiveDiscountCodes(context.Context, *ActiveDiscountsRequest) (*DiscountCodes, error)
	DeleteDiscountCode(context.Context, *DiscountCodeID) (*DiscountCodes, error)
}

func RegisterPlutusServer(s *grpc.Server, srv PlutusServer) {
	s.RegisterService(&_Plutus_serviceDesc, srv)
}

func _Plutus_NewCardToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCardTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).NewCardToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/NewCardToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).NewCardToken(ctx, req.(*NewCardTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_GetCardTokenOfCustomerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardTokenByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).GetCardTokenOfCustomerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/GetCardTokenOfCustomerByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).GetCardTokenOfCustomerByID(ctx, req.(*CardTokenByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_GetCardTokenOfCustomerByCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardTokenByCustomer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).GetCardTokenOfCustomerByCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/GetCardTokenOfCustomerByCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).GetCardTokenOfCustomerByCustomer(ctx, req.(*CardTokenByCustomer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_DeleteCardToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardTokenByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).DeleteCardToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/DeleteCardToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).DeleteCardToken(ctx, req.(*CardTokenByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_NewFastSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FastSale)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).NewFastSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/NewFastSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).NewFastSale(ctx, req.(*FastSale))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_NewSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).NewSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/NewSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).NewSale(ctx, req.(*NewSaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_GetSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).GetSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/GetSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).GetSale(ctx, req.(*SaleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_UpdateSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).UpdateSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/UpdateSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).UpdateSale(ctx, req.(*SaleUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_DeliverSaleReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverSaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).DeliverSaleReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/DeliverSaleReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).DeliverSaleReceipt(ctx, req.(*DeliverSaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_ChargeSaleByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).ChargeSaleByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/ChargeSaleByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).ChargeSaleByID(ctx, req.(*SaleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_ChargeSaleWithNativeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeWithNativeToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).ChargeSaleWithNativeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/ChargeSaleWithNativeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).ChargeSaleWithNativeToken(ctx, req.(*ChargeWithNativeToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_DoneSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).DoneSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/DoneSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).DoneSale(ctx, req.(*SaleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_CreateDiscountCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscountCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).CreateDiscountCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/CreateDiscountCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).CreateDiscountCode(ctx, req.(*DiscountCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_GetDiscountCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscountCodeID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).GetDiscountCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/GetDiscountCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).GetDiscountCode(ctx, req.(*DiscountCodeID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_ValidateDiscountCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscountCodeValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).ValidateDiscountCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/ValidateDiscountCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).ValidateDiscountCode(ctx, req.(*DiscountCodeValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_GetActiveDiscountCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveDiscountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).GetActiveDiscountCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/GetActiveDiscountCodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).GetActiveDiscountCodes(ctx, req.(*ActiveDiscountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_DeleteDiscountCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscountCodeID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).DeleteDiscountCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/DeleteDiscountCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).DeleteDiscountCode(ctx, req.(*DiscountCodeID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plutus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Plutus",
	HandlerType: (*PlutusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewCardToken",
			Handler:    _Plutus_NewCardToken_Handler,
		},
		{
			MethodName: "GetCardTokenOfCustomerByID",
			Handler:    _Plutus_GetCardTokenOfCustomerByID_Handler,
		},
		{
			MethodName: "GetCardTokenOfCustomerByCustomer",
			Handler:    _Plutus_GetCardTokenOfCustomerByCustomer_Handler,
		},
		{
			MethodName: "DeleteCardToken",
			Handler:    _Plutus_DeleteCardToken_Handler,
		},
		{
			MethodName: "NewFastSale",
			Handler:    _Plutus_NewFastSale_Handler,
		},
		{
			MethodName: "NewSale",
			Handler:    _Plutus_NewSale_Handler,
		},
		{
			MethodName: "GetSale",
			Handler:    _Plutus_GetSale_Handler,
		},
		{
			MethodName: "UpdateSale",
			Handler:    _Plutus_UpdateSale_Handler,
		},
		{
			MethodName: "DeliverSaleReceipt",
			Handler:    _Plutus_DeliverSaleReceipt_Handler,
		},
		{
			MethodName: "ChargeSaleByID",
			Handler:    _Plutus_ChargeSaleByID_Handler,
		},
		{
			MethodName: "ChargeSaleWithNativeToken",
			Handler:    _Plutus_ChargeSaleWithNativeToken_Handler,
		},
		{
			MethodName: "DoneSale",
			Handler:    _Plutus_DoneSale_Handler,
		},
		{
			MethodName: "CreateDiscountCode",
			Handler:    _Plutus_CreateDiscountCode_Handler,
		},
		{
			MethodName: "GetDiscountCode",
			Handler:    _Plutus_GetDiscountCode_Handler,
		},
		{
			MethodName: "ValidateDiscountCode",
			Handler:    _Plutus_ValidateDiscountCode_Handler,
		},
		{
			MethodName: "GetActiveDiscountCodes",
			Handler:    _Plutus_GetActiveDiscountCodes_Handler,
		},
		{
			MethodName: "DeleteDiscountCode",
			Handler:    _Plutus_DeleteDiscountCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plutus.proto",
}
