# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/plutus.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "NewCardTokenNativeRequest" do
    optional :token, :string, 1
    optional :customer, :message, 2, "Customer"
    optional :type, :enum, 3, "CardTokenType"
  end
  add_message "DiscountCodeValue" do
    optional :value, :string, 1
    optional :customerID, :string, 2
  end
  add_message "DiscountCodeExist" do
    optional :ok, :bool, 1
  end
  add_message "ChargeWithNativeToken" do
    optional :saleID, :string, 1
    optional :nativeToken, :string, 2
  end
  add_message "DiscountCodes" do
    repeated :discounts, :message, 1, "DiscountCode"
  end
  add_message "ActiveDiscountsRequest" do
    optional :until, :message, 1, "google.protobuf.Timestamp"
  end
  add_message "DiscountCodeID" do
    optional :id, :string, 1
  end
  add_message "DiscountCodeRequest" do
  end
  add_message "SaleUpdateRequest" do
    optional :id, :string, 1
    optional :updateData, :message, 2, "Sale"
  end
  add_message "DeliverSaleRequest" do
    optional :sale, :message, 1, "SaleIDRequest"
    optional :channel, :message, 2, "DeliveryChannel"
  end
  add_message "DeliverChannelResponse" do
    optional :message, :string, 1
    optional :code, :string, 2
  end
  add_message "DeliveryChannel" do
    oneof :identification do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :code, :string, 3
    end
  end
  add_message "SaleIDRequest" do
    optional :id, :string, 1
  end
  add_message "FastSale" do
    optional :customerEmail, :string, 1
    repeated :products, :message, 2, "Product"
  end
  add_message "NewSaleRequest" do
    optional :customer, :message, 1, "Customer"
    repeated :products, :message, 2, "Product"
  end
  add_message "CardTokenByID" do
    optional :id, :string, 1
  end
  add_message "CardTokenByCustomer" do
    optional :customer, :message, 1, "Customer"
  end
  add_message "NewCardTokenRequest" do
    optional :card, :message, 1, "Card"
    optional :customer, :message, 2, "Customer"
    optional :type, :enum, 3, "CardTokenType"
  end
  add_message "Card" do
    optional :number, :string, 1
    optional :expMont, :int32, 2
    optional :expYear, :int32, 3
    optional :cvc, :string, 4
  end
  add_message "Customer" do
    optional :id, :string, 1
    optional :email, :string, 2
    optional :name, :string, 3
    optional :phone, :string, 4
    optional :location, :message, 5, "Location"
  end
  add_message "Location" do
    optional :address, :string, 1
    optional :city, :string, 2
    optional :state, :string, 3
    optional :zip, :string, 4
  end
  add_message "CardToken" do
    optional :id, :string, 1
    optional :type, :enum, 2, "CardTokenType"
    optional :value, :string, 3
    optional :withCard, :message, 4, "EncodedCardDetails"
    optional :createdAt, :message, 5, "google.protobuf.Timestamp"
  end
  add_message "EncodedCardDetails" do
    optional :number, :string, 1
    optional :expirationYear, :int32, 2
    optional :customer, :message, 3, "Customer"
  end
  add_message "Sale" do
    optional :id, :string, 1
    optional :createdAt, :message, 2, "google.protobuf.Timestamp"
    optional :updatedAt, :message, 3, "google.protobuf.Timestamp"
    optional :state, :enum, 4, "SaleState"
    optional :customer, :message, 5, "Customer"
    repeated :products, :message, 6, "Product"
    repeated :discountCodes, :message, 7, "DiscountCode"
    optional :cardToken, :message, 8, "CardToken"
    optional :charge, :message, 9, "ChargeToken"
    optional :currencyToPay, :string, 10
  end
  add_message "Product" do
    optional :name, :string, 1
    optional :details, :string, 2
    optional :cost, :message, 3, "Cost"
  end
  add_message "Cost" do
    optional :amount, :double, 1
    optional :currency, :string, 2
  end
  add_message "ChargeToken" do
    optional :id, :string, 1
    optional :value, :string, 2
    optional :message, :string, 3
    optional :withCardToken, :message, 4, "CardToken"
    optional :createdAt, :message, 5, "google.protobuf.Timestamp"
  end
  add_message "DiscountCode" do
    optional :id, :string, 1
    optional :start, :message, 2, "google.protobuf.Timestamp"
    optional :end, :message, 3, "google.protobuf.Timestamp"
    optional :maxUses, :int32, 4
    repeated :uses, :message, 5, "DiscountUseRecord"
    optional :code, :string, 6
    optional :value, :message, 7, "Discount"
  end
  add_message "DiscountUseRecord" do
    optional :at, :message, 1, "google.protobuf.Timestamp"
    optional :by, :message, 2, "Customer"
  end
  add_message "Discount" do
    optional :type, :enum, 1, "DiscountType"
    optional :percent, :double, 2
    optional :amount, :double, 3
    optional :currency, :string, 4
  end
  add_enum "CardTokenType" do
    value :ONEUSE, 0
    value :RECURRENT, 1
  end
  add_enum "SaleState" do
    value :NULL, 0
    value :DRAFT, 1
    value :SIGNED, 2
    value :PAIDOUT, 3
    value :DONE, 4
  end
  add_enum "DiscountType" do
    value :STATIC, 0
    value :PERCENT, 1
  end
end

NewCardTokenNativeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("NewCardTokenNativeRequest").msgclass
DiscountCodeValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("DiscountCodeValue").msgclass
DiscountCodeExist = Google::Protobuf::DescriptorPool.generated_pool.lookup("DiscountCodeExist").msgclass
ChargeWithNativeToken = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChargeWithNativeToken").msgclass
DiscountCodes = Google::Protobuf::DescriptorPool.generated_pool.lookup("DiscountCodes").msgclass
ActiveDiscountsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ActiveDiscountsRequest").msgclass
DiscountCodeID = Google::Protobuf::DescriptorPool.generated_pool.lookup("DiscountCodeID").msgclass
DiscountCodeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("DiscountCodeRequest").msgclass
SaleUpdateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("SaleUpdateRequest").msgclass
DeliverSaleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("DeliverSaleRequest").msgclass
DeliverChannelResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("DeliverChannelResponse").msgclass
DeliveryChannel = Google::Protobuf::DescriptorPool.generated_pool.lookup("DeliveryChannel").msgclass
SaleIDRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("SaleIDRequest").msgclass
FastSale = Google::Protobuf::DescriptorPool.generated_pool.lookup("FastSale").msgclass
NewSaleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("NewSaleRequest").msgclass
CardTokenByID = Google::Protobuf::DescriptorPool.generated_pool.lookup("CardTokenByID").msgclass
CardTokenByCustomer = Google::Protobuf::DescriptorPool.generated_pool.lookup("CardTokenByCustomer").msgclass
NewCardTokenRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("NewCardTokenRequest").msgclass
Card = Google::Protobuf::DescriptorPool.generated_pool.lookup("Card").msgclass
Customer = Google::Protobuf::DescriptorPool.generated_pool.lookup("Customer").msgclass
Location = Google::Protobuf::DescriptorPool.generated_pool.lookup("Location").msgclass
CardToken = Google::Protobuf::DescriptorPool.generated_pool.lookup("CardToken").msgclass
EncodedCardDetails = Google::Protobuf::DescriptorPool.generated_pool.lookup("EncodedCardDetails").msgclass
Sale = Google::Protobuf::DescriptorPool.generated_pool.lookup("Sale").msgclass
Product = Google::Protobuf::DescriptorPool.generated_pool.lookup("Product").msgclass
Cost = Google::Protobuf::DescriptorPool.generated_pool.lookup("Cost").msgclass
ChargeToken = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChargeToken").msgclass
DiscountCode = Google::Protobuf::DescriptorPool.generated_pool.lookup("DiscountCode").msgclass
DiscountUseRecord = Google::Protobuf::DescriptorPool.generated_pool.lookup("DiscountUseRecord").msgclass
Discount = Google::Protobuf::DescriptorPool.generated_pool.lookup("Discount").msgclass
CardTokenType = Google::Protobuf::DescriptorPool.generated_pool.lookup("CardTokenType").enummodule
SaleState = Google::Protobuf::DescriptorPool.generated_pool.lookup("SaleState").enummodule
DiscountType = Google::Protobuf::DescriptorPool.generated_pool.lookup("DiscountType").enummodule
