// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/plutus.proto

package plutus

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CardTokenType int32

const (
	CardTokenType_ONEUSE    CardTokenType = 0
	CardTokenType_RECURRENT CardTokenType = 1
)

var CardTokenType_name = map[int32]string{
	0: "ONEUSE",
	1: "RECURRENT",
}

var CardTokenType_value = map[string]int32{
	"ONEUSE":    0,
	"RECURRENT": 1,
}

func (x CardTokenType) String() string {
	return proto.EnumName(CardTokenType_name, int32(x))
}

func (CardTokenType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{0}
}

type SaleState int32

const (
	SaleState_NULL    SaleState = 0
	SaleState_DRAFT   SaleState = 1
	SaleState_SIGNED  SaleState = 2
	SaleState_PAIDOUT SaleState = 3
	SaleState_DONE    SaleState = 4
)

var SaleState_name = map[int32]string{
	0: "NULL",
	1: "DRAFT",
	2: "SIGNED",
	3: "PAIDOUT",
	4: "DONE",
}

var SaleState_value = map[string]int32{
	"NULL":    0,
	"DRAFT":   1,
	"SIGNED":  2,
	"PAIDOUT": 3,
	"DONE":    4,
}

func (x SaleState) String() string {
	return proto.EnumName(SaleState_name, int32(x))
}

func (SaleState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{1}
}

type DiscountType int32

const (
	DiscountType_STATIC  DiscountType = 0
	DiscountType_PERCENT DiscountType = 1
)

var DiscountType_name = map[int32]string{
	0: "STATIC",
	1: "PERCENT",
}

var DiscountType_value = map[string]int32{
	"STATIC":  0,
	"PERCENT": 1,
}

func (x DiscountType) String() string {
	return proto.EnumName(DiscountType_name, int32(x))
}

func (DiscountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{2}
}

type SalesFilterRequest struct {
	Page                 int32                `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	ItemsPerPage         int32                `protobuf:"varint,3,opt,name=itemsPerPage,proto3" json:"itemsPerPage,omitempty"`
	From                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	ByCardTokenID        string               `protobuf:"bytes,6,opt,name=byCardTokenID,proto3" json:"byCardTokenID,omitempty"`
	ByChargeTokenID      string               `protobuf:"bytes,7,opt,name=byChargeTokenID,proto3" json:"byChargeTokenID,omitempty"`
	ByStates             []SaleState          `protobuf:"varint,5,rep,packed,name=byStates,proto3,enum=SaleState" json:"byStates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SalesFilterRequest) Reset()         { *m = SalesFilterRequest{} }
func (m *SalesFilterRequest) String() string { return proto.CompactTextString(m) }
func (*SalesFilterRequest) ProtoMessage()    {}
func (*SalesFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{0}
}

func (m *SalesFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SalesFilterRequest.Unmarshal(m, b)
}
func (m *SalesFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SalesFilterRequest.Marshal(b, m, deterministic)
}
func (m *SalesFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SalesFilterRequest.Merge(m, src)
}
func (m *SalesFilterRequest) XXX_Size() int {
	return xxx_messageInfo_SalesFilterRequest.Size(m)
}
func (m *SalesFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SalesFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SalesFilterRequest proto.InternalMessageInfo

func (m *SalesFilterRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SalesFilterRequest) GetItemsPerPage() int32 {
	if m != nil {
		return m.ItemsPerPage
	}
	return 0
}

func (m *SalesFilterRequest) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *SalesFilterRequest) GetTo() *timestamp.Timestamp {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *SalesFilterRequest) GetByCardTokenID() string {
	if m != nil {
		return m.ByCardTokenID
	}
	return ""
}

func (m *SalesFilterRequest) GetByChargeTokenID() string {
	if m != nil {
		return m.ByChargeTokenID
	}
	return ""
}

func (m *SalesFilterRequest) GetByStates() []SaleState {
	if m != nil {
		return m.ByStates
	}
	return nil
}

type Sales struct {
	Sales                []*Sale  `protobuf:"bytes,1,rep,name=sales,proto3" json:"sales,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Next                 int32    `protobuf:"varint,4,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sales) Reset()         { *m = Sales{} }
func (m *Sales) String() string { return proto.CompactTextString(m) }
func (*Sales) ProtoMessage()    {}
func (*Sales) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{1}
}

func (m *Sales) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sales.Unmarshal(m, b)
}
func (m *Sales) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sales.Marshal(b, m, deterministic)
}
func (m *Sales) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sales.Merge(m, src)
}
func (m *Sales) XXX_Size() int {
	return xxx_messageInfo_Sales.Size(m)
}
func (m *Sales) XXX_DiscardUnknown() {
	xxx_messageInfo_Sales.DiscardUnknown(m)
}

var xxx_messageInfo_Sales proto.InternalMessageInfo

func (m *Sales) GetSales() []*Sale {
	if m != nil {
		return m.Sales
	}
	return nil
}

func (m *Sales) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Sales) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Sales) GetNext() int32 {
	if m != nil {
		return m.Next
	}
	return 0
}

type ChargeSaleRequest struct {
	SaleID               string   `protobuf:"bytes,1,opt,name=saleID,proto3" json:"saleID,omitempty"`
	CardTokenID          string   `protobuf:"bytes,2,opt,name=cardTokenID,proto3" json:"cardTokenID,omitempty"`
	Details              string   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeSaleRequest) Reset()         { *m = ChargeSaleRequest{} }
func (m *ChargeSaleRequest) String() string { return proto.CompactTextString(m) }
func (*ChargeSaleRequest) ProtoMessage()    {}
func (*ChargeSaleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{2}
}

func (m *ChargeSaleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeSaleRequest.Unmarshal(m, b)
}
func (m *ChargeSaleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeSaleRequest.Marshal(b, m, deterministic)
}
func (m *ChargeSaleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeSaleRequest.Merge(m, src)
}
func (m *ChargeSaleRequest) XXX_Size() int {
	return xxx_messageInfo_ChargeSaleRequest.Size(m)
}
func (m *ChargeSaleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeSaleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeSaleRequest proto.InternalMessageInfo

func (m *ChargeSaleRequest) GetSaleID() string {
	if m != nil {
		return m.SaleID
	}
	return ""
}

func (m *ChargeSaleRequest) GetCardTokenID() string {
	if m != nil {
		return m.CardTokenID
	}
	return ""
}

func (m *ChargeSaleRequest) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type NewCardTokenNativeRequest struct {
	Token                string        `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Customer             *Customer     `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	Type                 CardTokenType `protobuf:"varint,3,opt,name=type,proto3,enum=CardTokenType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NewCardTokenNativeRequest) Reset()         { *m = NewCardTokenNativeRequest{} }
func (m *NewCardTokenNativeRequest) String() string { return proto.CompactTextString(m) }
func (*NewCardTokenNativeRequest) ProtoMessage()    {}
func (*NewCardTokenNativeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{3}
}

func (m *NewCardTokenNativeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCardTokenNativeRequest.Unmarshal(m, b)
}
func (m *NewCardTokenNativeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCardTokenNativeRequest.Marshal(b, m, deterministic)
}
func (m *NewCardTokenNativeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCardTokenNativeRequest.Merge(m, src)
}
func (m *NewCardTokenNativeRequest) XXX_Size() int {
	return xxx_messageInfo_NewCardTokenNativeRequest.Size(m)
}
func (m *NewCardTokenNativeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCardTokenNativeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewCardTokenNativeRequest proto.InternalMessageInfo

func (m *NewCardTokenNativeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *NewCardTokenNativeRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *NewCardTokenNativeRequest) GetType() CardTokenType {
	if m != nil {
		return m.Type
	}
	return CardTokenType_ONEUSE
}

type DiscountCodeValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	CustomerID           string   `protobuf:"bytes,2,opt,name=customerID,proto3" json:"customerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountCodeValue) Reset()         { *m = DiscountCodeValue{} }
func (m *DiscountCodeValue) String() string { return proto.CompactTextString(m) }
func (*DiscountCodeValue) ProtoMessage()    {}
func (*DiscountCodeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{4}
}

func (m *DiscountCodeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountCodeValue.Unmarshal(m, b)
}
func (m *DiscountCodeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountCodeValue.Marshal(b, m, deterministic)
}
func (m *DiscountCodeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountCodeValue.Merge(m, src)
}
func (m *DiscountCodeValue) XXX_Size() int {
	return xxx_messageInfo_DiscountCodeValue.Size(m)
}
func (m *DiscountCodeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountCodeValue.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountCodeValue proto.InternalMessageInfo

func (m *DiscountCodeValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *DiscountCodeValue) GetCustomerID() string {
	if m != nil {
		return m.CustomerID
	}
	return ""
}

type DiscountCodeExist struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountCodeExist) Reset()         { *m = DiscountCodeExist{} }
func (m *DiscountCodeExist) String() string { return proto.CompactTextString(m) }
func (*DiscountCodeExist) ProtoMessage()    {}
func (*DiscountCodeExist) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{5}
}

func (m *DiscountCodeExist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountCodeExist.Unmarshal(m, b)
}
func (m *DiscountCodeExist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountCodeExist.Marshal(b, m, deterministic)
}
func (m *DiscountCodeExist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountCodeExist.Merge(m, src)
}
func (m *DiscountCodeExist) XXX_Size() int {
	return xxx_messageInfo_DiscountCodeExist.Size(m)
}
func (m *DiscountCodeExist) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountCodeExist.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountCodeExist proto.InternalMessageInfo

func (m *DiscountCodeExist) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ChargeWithNativeToken struct {
	SaleID               string   `protobuf:"bytes,1,opt,name=saleID,proto3" json:"saleID,omitempty"`
	NativeToken          string   `protobuf:"bytes,2,opt,name=nativeToken,proto3" json:"nativeToken,omitempty"`
	Details              string   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeWithNativeToken) Reset()         { *m = ChargeWithNativeToken{} }
func (m *ChargeWithNativeToken) String() string { return proto.CompactTextString(m) }
func (*ChargeWithNativeToken) ProtoMessage()    {}
func (*ChargeWithNativeToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{6}
}

func (m *ChargeWithNativeToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeWithNativeToken.Unmarshal(m, b)
}
func (m *ChargeWithNativeToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeWithNativeToken.Marshal(b, m, deterministic)
}
func (m *ChargeWithNativeToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeWithNativeToken.Merge(m, src)
}
func (m *ChargeWithNativeToken) XXX_Size() int {
	return xxx_messageInfo_ChargeWithNativeToken.Size(m)
}
func (m *ChargeWithNativeToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeWithNativeToken.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeWithNativeToken proto.InternalMessageInfo

func (m *ChargeWithNativeToken) GetSaleID() string {
	if m != nil {
		return m.SaleID
	}
	return ""
}

func (m *ChargeWithNativeToken) GetNativeToken() string {
	if m != nil {
		return m.NativeToken
	}
	return ""
}

func (m *ChargeWithNativeToken) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type DiscountCodes struct {
	Discounts            []*DiscountCode `protobuf:"bytes,1,rep,name=discounts,proto3" json:"discounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DiscountCodes) Reset()         { *m = DiscountCodes{} }
func (m *DiscountCodes) String() string { return proto.CompactTextString(m) }
func (*DiscountCodes) ProtoMessage()    {}
func (*DiscountCodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{7}
}

func (m *DiscountCodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountCodes.Unmarshal(m, b)
}
func (m *DiscountCodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountCodes.Marshal(b, m, deterministic)
}
func (m *DiscountCodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountCodes.Merge(m, src)
}
func (m *DiscountCodes) XXX_Size() int {
	return xxx_messageInfo_DiscountCodes.Size(m)
}
func (m *DiscountCodes) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountCodes.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountCodes proto.InternalMessageInfo

func (m *DiscountCodes) GetDiscounts() []*DiscountCode {
	if m != nil {
		return m.Discounts
	}
	return nil
}

type ActiveDiscountsRequest struct {
	Until                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=until,proto3" json:"until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ActiveDiscountsRequest) Reset()         { *m = ActiveDiscountsRequest{} }
func (m *ActiveDiscountsRequest) String() string { return proto.CompactTextString(m) }
func (*ActiveDiscountsRequest) ProtoMessage()    {}
func (*ActiveDiscountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{8}
}

func (m *ActiveDiscountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveDiscountsRequest.Unmarshal(m, b)
}
func (m *ActiveDiscountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveDiscountsRequest.Marshal(b, m, deterministic)
}
func (m *ActiveDiscountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveDiscountsRequest.Merge(m, src)
}
func (m *ActiveDiscountsRequest) XXX_Size() int {
	return xxx_messageInfo_ActiveDiscountsRequest.Size(m)
}
func (m *ActiveDiscountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveDiscountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveDiscountsRequest proto.InternalMessageInfo

func (m *ActiveDiscountsRequest) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type DiscountCodeID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountCodeID) Reset()         { *m = DiscountCodeID{} }
func (m *DiscountCodeID) String() string { return proto.CompactTextString(m) }
func (*DiscountCodeID) ProtoMessage()    {}
func (*DiscountCodeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{9}
}

func (m *DiscountCodeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountCodeID.Unmarshal(m, b)
}
func (m *DiscountCodeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountCodeID.Marshal(b, m, deterministic)
}
func (m *DiscountCodeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountCodeID.Merge(m, src)
}
func (m *DiscountCodeID) XXX_Size() int {
	return xxx_messageInfo_DiscountCodeID.Size(m)
}
func (m *DiscountCodeID) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountCodeID.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountCodeID proto.InternalMessageInfo

func (m *DiscountCodeID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DiscountCodeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountCodeRequest) Reset()         { *m = DiscountCodeRequest{} }
func (m *DiscountCodeRequest) String() string { return proto.CompactTextString(m) }
func (*DiscountCodeRequest) ProtoMessage()    {}
func (*DiscountCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{10}
}

func (m *DiscountCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountCodeRequest.Unmarshal(m, b)
}
func (m *DiscountCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountCodeRequest.Marshal(b, m, deterministic)
}
func (m *DiscountCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountCodeRequest.Merge(m, src)
}
func (m *DiscountCodeRequest) XXX_Size() int {
	return xxx_messageInfo_DiscountCodeRequest.Size(m)
}
func (m *DiscountCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountCodeRequest proto.InternalMessageInfo

type SaleUpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdateData           *Sale    `protobuf:"bytes,2,opt,name=updateData,proto3" json:"updateData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaleUpdateRequest) Reset()         { *m = SaleUpdateRequest{} }
func (m *SaleUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*SaleUpdateRequest) ProtoMessage()    {}
func (*SaleUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{11}
}

func (m *SaleUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaleUpdateRequest.Unmarshal(m, b)
}
func (m *SaleUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaleUpdateRequest.Marshal(b, m, deterministic)
}
func (m *SaleUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaleUpdateRequest.Merge(m, src)
}
func (m *SaleUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_SaleUpdateRequest.Size(m)
}
func (m *SaleUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaleUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaleUpdateRequest proto.InternalMessageInfo

func (m *SaleUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SaleUpdateRequest) GetUpdateData() *Sale {
	if m != nil {
		return m.UpdateData
	}
	return nil
}

type DeliverSaleRequest struct {
	SaleID               string            `protobuf:"bytes,1,opt,name=saleID,proto3" json:"saleID,omitempty"`
	ChannelName          string            `protobuf:"bytes,2,opt,name=channelName,proto3" json:"channelName,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeliverSaleRequest) Reset()         { *m = DeliverSaleRequest{} }
func (m *DeliverSaleRequest) String() string { return proto.CompactTextString(m) }
func (*DeliverSaleRequest) ProtoMessage()    {}
func (*DeliverSaleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{12}
}

func (m *DeliverSaleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverSaleRequest.Unmarshal(m, b)
}
func (m *DeliverSaleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverSaleRequest.Marshal(b, m, deterministic)
}
func (m *DeliverSaleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverSaleRequest.Merge(m, src)
}
func (m *DeliverSaleRequest) XXX_Size() int {
	return xxx_messageInfo_DeliverSaleRequest.Size(m)
}
func (m *DeliverSaleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverSaleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverSaleRequest proto.InternalMessageInfo

func (m *DeliverSaleRequest) GetSaleID() string {
	if m != nil {
		return m.SaleID
	}
	return ""
}

func (m *DeliverSaleRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *DeliverSaleRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type DeliverChannelResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliverChannelResponse) Reset()         { *m = DeliverChannelResponse{} }
func (m *DeliverChannelResponse) String() string { return proto.CompactTextString(m) }
func (*DeliverChannelResponse) ProtoMessage()    {}
func (*DeliverChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{13}
}

func (m *DeliverChannelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverChannelResponse.Unmarshal(m, b)
}
func (m *DeliverChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverChannelResponse.Marshal(b, m, deterministic)
}
func (m *DeliverChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverChannelResponse.Merge(m, src)
}
func (m *DeliverChannelResponse) XXX_Size() int {
	return xxx_messageInfo_DeliverChannelResponse.Size(m)
}
func (m *DeliverChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverChannelResponse proto.InternalMessageInfo

func (m *DeliverChannelResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeliverChannelResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SaleIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaleIDRequest) Reset()         { *m = SaleIDRequest{} }
func (m *SaleIDRequest) String() string { return proto.CompactTextString(m) }
func (*SaleIDRequest) ProtoMessage()    {}
func (*SaleIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{14}
}

func (m *SaleIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaleIDRequest.Unmarshal(m, b)
}
func (m *SaleIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaleIDRequest.Marshal(b, m, deterministic)
}
func (m *SaleIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaleIDRequest.Merge(m, src)
}
func (m *SaleIDRequest) XXX_Size() int {
	return xxx_messageInfo_SaleIDRequest.Size(m)
}
func (m *SaleIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaleIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaleIDRequest proto.InternalMessageInfo

func (m *SaleIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FastSale struct {
	CustomerEmail        string     `protobuf:"bytes,1,opt,name=customerEmail,proto3" json:"customerEmail,omitempty"`
	Products             []*Product `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FastSale) Reset()         { *m = FastSale{} }
func (m *FastSale) String() string { return proto.CompactTextString(m) }
func (*FastSale) ProtoMessage()    {}
func (*FastSale) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{15}
}

func (m *FastSale) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FastSale.Unmarshal(m, b)
}
func (m *FastSale) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FastSale.Marshal(b, m, deterministic)
}
func (m *FastSale) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastSale.Merge(m, src)
}
func (m *FastSale) XXX_Size() int {
	return xxx_messageInfo_FastSale.Size(m)
}
func (m *FastSale) XXX_DiscardUnknown() {
	xxx_messageInfo_FastSale.DiscardUnknown(m)
}

var xxx_messageInfo_FastSale proto.InternalMessageInfo

func (m *FastSale) GetCustomerEmail() string {
	if m != nil {
		return m.CustomerEmail
	}
	return ""
}

func (m *FastSale) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type NewSaleRequest struct {
	Customer             *Customer  `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Products             []*Product `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NewSaleRequest) Reset()         { *m = NewSaleRequest{} }
func (m *NewSaleRequest) String() string { return proto.CompactTextString(m) }
func (*NewSaleRequest) ProtoMessage()    {}
func (*NewSaleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{16}
}

func (m *NewSaleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSaleRequest.Unmarshal(m, b)
}
func (m *NewSaleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSaleRequest.Marshal(b, m, deterministic)
}
func (m *NewSaleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSaleRequest.Merge(m, src)
}
func (m *NewSaleRequest) XXX_Size() int {
	return xxx_messageInfo_NewSaleRequest.Size(m)
}
func (m *NewSaleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSaleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewSaleRequest proto.InternalMessageInfo

func (m *NewSaleRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *NewSaleRequest) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type CardTokenByID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardTokenByID) Reset()         { *m = CardTokenByID{} }
func (m *CardTokenByID) String() string { return proto.CompactTextString(m) }
func (*CardTokenByID) ProtoMessage()    {}
func (*CardTokenByID) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{17}
}

func (m *CardTokenByID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardTokenByID.Unmarshal(m, b)
}
func (m *CardTokenByID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardTokenByID.Marshal(b, m, deterministic)
}
func (m *CardTokenByID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardTokenByID.Merge(m, src)
}
func (m *CardTokenByID) XXX_Size() int {
	return xxx_messageInfo_CardTokenByID.Size(m)
}
func (m *CardTokenByID) XXX_DiscardUnknown() {
	xxx_messageInfo_CardTokenByID.DiscardUnknown(m)
}

var xxx_messageInfo_CardTokenByID proto.InternalMessageInfo

func (m *CardTokenByID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CardTokenByCustomer struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CardTokenByCustomer) Reset()         { *m = CardTokenByCustomer{} }
func (m *CardTokenByCustomer) String() string { return proto.CompactTextString(m) }
func (*CardTokenByCustomer) ProtoMessage()    {}
func (*CardTokenByCustomer) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{18}
}

func (m *CardTokenByCustomer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardTokenByCustomer.Unmarshal(m, b)
}
func (m *CardTokenByCustomer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardTokenByCustomer.Marshal(b, m, deterministic)
}
func (m *CardTokenByCustomer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardTokenByCustomer.Merge(m, src)
}
func (m *CardTokenByCustomer) XXX_Size() int {
	return xxx_messageInfo_CardTokenByCustomer.Size(m)
}
func (m *CardTokenByCustomer) XXX_DiscardUnknown() {
	xxx_messageInfo_CardTokenByCustomer.DiscardUnknown(m)
}

var xxx_messageInfo_CardTokenByCustomer proto.InternalMessageInfo

func (m *CardTokenByCustomer) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type NewCardTokenRequest struct {
	Card                 *Card         `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	Customer             *Customer     `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	Type                 CardTokenType `protobuf:"varint,3,opt,name=type,proto3,enum=CardTokenType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NewCardTokenRequest) Reset()         { *m = NewCardTokenRequest{} }
func (m *NewCardTokenRequest) String() string { return proto.CompactTextString(m) }
func (*NewCardTokenRequest) ProtoMessage()    {}
func (*NewCardTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{19}
}

func (m *NewCardTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCardTokenRequest.Unmarshal(m, b)
}
func (m *NewCardTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCardTokenRequest.Marshal(b, m, deterministic)
}
func (m *NewCardTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCardTokenRequest.Merge(m, src)
}
func (m *NewCardTokenRequest) XXX_Size() int {
	return xxx_messageInfo_NewCardTokenRequest.Size(m)
}
func (m *NewCardTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCardTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewCardTokenRequest proto.InternalMessageInfo

func (m *NewCardTokenRequest) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

func (m *NewCardTokenRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *NewCardTokenRequest) GetType() CardTokenType {
	if m != nil {
		return m.Type
	}
	return CardTokenType_ONEUSE
}

type Card struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	ExpMont              int32    `protobuf:"varint,2,opt,name=expMont,proto3" json:"expMont,omitempty"`
	ExpYear              int32    `protobuf:"varint,3,opt,name=expYear,proto3" json:"expYear,omitempty"`
	Cvc                  string   `protobuf:"bytes,4,opt,name=cvc,proto3" json:"cvc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{20}
}

func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (m *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(m, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Card) GetExpMont() int32 {
	if m != nil {
		return m.ExpMont
	}
	return 0
}

func (m *Card) GetExpYear() int32 {
	if m != nil {
		return m.ExpYear
	}
	return 0
}

func (m *Card) GetCvc() string {
	if m != nil {
		return m.Cvc
	}
	return ""
}

type Customer struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string    `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Person               string    `protobuf:"bytes,6,opt,name=person,proto3" json:"person,omitempty"`
	Phone                string    `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Location             *Location `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{21}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Customer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Customer) GetPerson() string {
	if m != nil {
		return m.Person
	}
	return ""
}

func (m *Customer) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Customer) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Location struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{22}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Location) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type CardToken struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 CardTokenType        `protobuf:"varint,2,opt,name=type,proto3,enum=CardTokenType" json:"type,omitempty"`
	Value                string               `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	WithCard             *EncodedCardDetails  `protobuf:"bytes,4,opt,name=withCard,proto3" json:"withCard,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CardToken) Reset()         { *m = CardToken{} }
func (m *CardToken) String() string { return proto.CompactTextString(m) }
func (*CardToken) ProtoMessage()    {}
func (*CardToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{23}
}

func (m *CardToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardToken.Unmarshal(m, b)
}
func (m *CardToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardToken.Marshal(b, m, deterministic)
}
func (m *CardToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardToken.Merge(m, src)
}
func (m *CardToken) XXX_Size() int {
	return xxx_messageInfo_CardToken.Size(m)
}
func (m *CardToken) XXX_DiscardUnknown() {
	xxx_messageInfo_CardToken.DiscardUnknown(m)
}

var xxx_messageInfo_CardToken proto.InternalMessageInfo

func (m *CardToken) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CardToken) GetType() CardTokenType {
	if m != nil {
		return m.Type
	}
	return CardTokenType_ONEUSE
}

func (m *CardToken) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *CardToken) GetWithCard() *EncodedCardDetails {
	if m != nil {
		return m.WithCard
	}
	return nil
}

func (m *CardToken) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type EncodedCardDetails struct {
	Number               string    `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	ExpirationYear       int32     `protobuf:"varint,2,opt,name=expirationYear,proto3" json:"expirationYear,omitempty"`
	Customer             *Customer `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EncodedCardDetails) Reset()         { *m = EncodedCardDetails{} }
func (m *EncodedCardDetails) String() string { return proto.CompactTextString(m) }
func (*EncodedCardDetails) ProtoMessage()    {}
func (*EncodedCardDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{24}
}

func (m *EncodedCardDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncodedCardDetails.Unmarshal(m, b)
}
func (m *EncodedCardDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncodedCardDetails.Marshal(b, m, deterministic)
}
func (m *EncodedCardDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodedCardDetails.Merge(m, src)
}
func (m *EncodedCardDetails) XXX_Size() int {
	return xxx_messageInfo_EncodedCardDetails.Size(m)
}
func (m *EncodedCardDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodedCardDetails.DiscardUnknown(m)
}

var xxx_messageInfo_EncodedCardDetails proto.InternalMessageInfo

func (m *EncodedCardDetails) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *EncodedCardDetails) GetExpirationYear() int32 {
	if m != nil {
		return m.ExpirationYear
	}
	return 0
}

func (m *EncodedCardDetails) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type Sale struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	State                SaleState            `protobuf:"varint,4,opt,name=state,proto3,enum=SaleState" json:"state,omitempty"`
	Customer             *Customer            `protobuf:"bytes,5,opt,name=customer,proto3" json:"customer,omitempty"`
	Products             []*Product           `protobuf:"bytes,6,rep,name=products,proto3" json:"products,omitempty"`
	DiscountCodes        []*DiscountCode      `protobuf:"bytes,7,rep,name=discountCodes,proto3" json:"discountCodes,omitempty"`
	CardToken            *CardToken           `protobuf:"bytes,8,opt,name=cardToken,proto3" json:"cardToken,omitempty"`
	Charge               *ChargeToken         `protobuf:"bytes,9,opt,name=charge,proto3" json:"charge,omitempty"`
	CurrencyToPay        string               `protobuf:"bytes,10,opt,name=currencyToPay,proto3" json:"currencyToPay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Sale) Reset()         { *m = Sale{} }
func (m *Sale) String() string { return proto.CompactTextString(m) }
func (*Sale) ProtoMessage()    {}
func (*Sale) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{25}
}

func (m *Sale) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sale.Unmarshal(m, b)
}
func (m *Sale) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sale.Marshal(b, m, deterministic)
}
func (m *Sale) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sale.Merge(m, src)
}
func (m *Sale) XXX_Size() int {
	return xxx_messageInfo_Sale.Size(m)
}
func (m *Sale) XXX_DiscardUnknown() {
	xxx_messageInfo_Sale.DiscardUnknown(m)
}

var xxx_messageInfo_Sale proto.InternalMessageInfo

func (m *Sale) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Sale) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Sale) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Sale) GetState() SaleState {
	if m != nil {
		return m.State
	}
	return SaleState_NULL
}

func (m *Sale) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *Sale) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Sale) GetDiscountCodes() []*DiscountCode {
	if m != nil {
		return m.DiscountCodes
	}
	return nil
}

func (m *Sale) GetCardToken() *CardToken {
	if m != nil {
		return m.CardToken
	}
	return nil
}

func (m *Sale) GetCharge() *ChargeToken {
	if m != nil {
		return m.Charge
	}
	return nil
}

func (m *Sale) GetCurrencyToPay() string {
	if m != nil {
		return m.CurrencyToPay
	}
	return ""
}

type Product struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Details              string   `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	Cost                 *Cost    `protobuf:"bytes,3,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{26}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Product) GetCost() *Cost {
	if m != nil {
		return m.Cost
	}
	return nil
}

type Cost struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cost) Reset()         { *m = Cost{} }
func (m *Cost) String() string { return proto.CompactTextString(m) }
func (*Cost) ProtoMessage()    {}
func (*Cost) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{27}
}

func (m *Cost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cost.Unmarshal(m, b)
}
func (m *Cost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cost.Marshal(b, m, deterministic)
}
func (m *Cost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cost.Merge(m, src)
}
func (m *Cost) XXX_Size() int {
	return xxx_messageInfo_Cost.Size(m)
}
func (m *Cost) XXX_DiscardUnknown() {
	xxx_messageInfo_Cost.DiscardUnknown(m)
}

var xxx_messageInfo_Cost proto.InternalMessageInfo

func (m *Cost) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Cost) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type ChargeToken struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                string               `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	WithCardToken        *CardToken           `protobuf:"bytes,4,opt,name=withCardToken,proto3" json:"withCardToken,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChargeToken) Reset()         { *m = ChargeToken{} }
func (m *ChargeToken) String() string { return proto.CompactTextString(m) }
func (*ChargeToken) ProtoMessage()    {}
func (*ChargeToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{28}
}

func (m *ChargeToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeToken.Unmarshal(m, b)
}
func (m *ChargeToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeToken.Marshal(b, m, deterministic)
}
func (m *ChargeToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeToken.Merge(m, src)
}
func (m *ChargeToken) XXX_Size() int {
	return xxx_messageInfo_ChargeToken.Size(m)
}
func (m *ChargeToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeToken.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeToken proto.InternalMessageInfo

func (m *ChargeToken) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChargeToken) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ChargeToken) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChargeToken) GetWithCardToken() *CardToken {
	if m != nil {
		return m.WithCardToken
	}
	return nil
}

func (m *ChargeToken) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type DiscountCode struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	MaxUses              int32                `protobuf:"varint,4,opt,name=maxUses,proto3" json:"maxUses,omitempty"`
	Uses                 []*DiscountUseRecord `protobuf:"bytes,5,rep,name=uses,proto3" json:"uses,omitempty"`
	Code                 string               `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Value                *Discount            `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DiscountCode) Reset()         { *m = DiscountCode{} }
func (m *DiscountCode) String() string { return proto.CompactTextString(m) }
func (*DiscountCode) ProtoMessage()    {}
func (*DiscountCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{29}
}

func (m *DiscountCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountCode.Unmarshal(m, b)
}
func (m *DiscountCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountCode.Marshal(b, m, deterministic)
}
func (m *DiscountCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountCode.Merge(m, src)
}
func (m *DiscountCode) XXX_Size() int {
	return xxx_messageInfo_DiscountCode.Size(m)
}
func (m *DiscountCode) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountCode.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountCode proto.InternalMessageInfo

func (m *DiscountCode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DiscountCode) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *DiscountCode) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *DiscountCode) GetMaxUses() int32 {
	if m != nil {
		return m.MaxUses
	}
	return 0
}

func (m *DiscountCode) GetUses() []*DiscountUseRecord {
	if m != nil {
		return m.Uses
	}
	return nil
}

func (m *DiscountCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DiscountCode) GetValue() *Discount {
	if m != nil {
		return m.Value
	}
	return nil
}

type DiscountUseRecord struct {
	At                   *timestamp.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	By                   *Customer            `protobuf:"bytes,2,opt,name=by,proto3" json:"by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DiscountUseRecord) Reset()         { *m = DiscountUseRecord{} }
func (m *DiscountUseRecord) String() string { return proto.CompactTextString(m) }
func (*DiscountUseRecord) ProtoMessage()    {}
func (*DiscountUseRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{30}
}

func (m *DiscountUseRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountUseRecord.Unmarshal(m, b)
}
func (m *DiscountUseRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountUseRecord.Marshal(b, m, deterministic)
}
func (m *DiscountUseRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountUseRecord.Merge(m, src)
}
func (m *DiscountUseRecord) XXX_Size() int {
	return xxx_messageInfo_DiscountUseRecord.Size(m)
}
func (m *DiscountUseRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountUseRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountUseRecord proto.InternalMessageInfo

func (m *DiscountUseRecord) GetAt() *timestamp.Timestamp {
	if m != nil {
		return m.At
	}
	return nil
}

func (m *DiscountUseRecord) GetBy() *Customer {
	if m != nil {
		return m.By
	}
	return nil
}

type Discount struct {
	Type                 DiscountType `protobuf:"varint,1,opt,name=type,proto3,enum=DiscountType" json:"type,omitempty"`
	Percent              float64      `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent,omitempty"`
	Amount               float64      `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string       `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Discount) Reset()         { *m = Discount{} }
func (m *Discount) String() string { return proto.CompactTextString(m) }
func (*Discount) ProtoMessage()    {}
func (*Discount) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f31399d60808ca, []int{31}
}

func (m *Discount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discount.Unmarshal(m, b)
}
func (m *Discount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discount.Marshal(b, m, deterministic)
}
func (m *Discount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discount.Merge(m, src)
}
func (m *Discount) XXX_Size() int {
	return xxx_messageInfo_Discount.Size(m)
}
func (m *Discount) XXX_DiscardUnknown() {
	xxx_messageInfo_Discount.DiscardUnknown(m)
}

var xxx_messageInfo_Discount proto.InternalMessageInfo

func (m *Discount) GetType() DiscountType {
	if m != nil {
		return m.Type
	}
	return DiscountType_STATIC
}

func (m *Discount) GetPercent() float64 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *Discount) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Discount) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func init() {
	proto.RegisterEnum("CardTokenType", CardTokenType_name, CardTokenType_value)
	proto.RegisterEnum("SaleState", SaleState_name, SaleState_value)
	proto.RegisterEnum("DiscountType", DiscountType_name, DiscountType_value)
	proto.RegisterType((*SalesFilterRequest)(nil), "SalesFilterRequest")
	proto.RegisterType((*Sales)(nil), "Sales")
	proto.RegisterType((*ChargeSaleRequest)(nil), "ChargeSaleRequest")
	proto.RegisterType((*NewCardTokenNativeRequest)(nil), "NewCardTokenNativeRequest")
	proto.RegisterType((*DiscountCodeValue)(nil), "DiscountCodeValue")
	proto.RegisterType((*DiscountCodeExist)(nil), "DiscountCodeExist")
	proto.RegisterType((*ChargeWithNativeToken)(nil), "ChargeWithNativeToken")
	proto.RegisterType((*DiscountCodes)(nil), "DiscountCodes")
	proto.RegisterType((*ActiveDiscountsRequest)(nil), "ActiveDiscountsRequest")
	proto.RegisterType((*DiscountCodeID)(nil), "DiscountCodeID")
	proto.RegisterType((*DiscountCodeRequest)(nil), "DiscountCodeRequest")
	proto.RegisterType((*SaleUpdateRequest)(nil), "SaleUpdateRequest")
	proto.RegisterType((*DeliverSaleRequest)(nil), "DeliverSaleRequest")
	proto.RegisterMapType((map[string]string)(nil), "DeliverSaleRequest.MetadataEntry")
	proto.RegisterType((*DeliverChannelResponse)(nil), "DeliverChannelResponse")
	proto.RegisterType((*SaleIDRequest)(nil), "SaleIDRequest")
	proto.RegisterType((*FastSale)(nil), "FastSale")
	proto.RegisterType((*NewSaleRequest)(nil), "NewSaleRequest")
	proto.RegisterType((*CardTokenByID)(nil), "CardTokenByID")
	proto.RegisterType((*CardTokenByCustomer)(nil), "CardTokenByCustomer")
	proto.RegisterType((*NewCardTokenRequest)(nil), "NewCardTokenRequest")
	proto.RegisterType((*Card)(nil), "Card")
	proto.RegisterType((*Customer)(nil), "Customer")
	proto.RegisterType((*Location)(nil), "Location")
	proto.RegisterType((*CardToken)(nil), "CardToken")
	proto.RegisterType((*EncodedCardDetails)(nil), "EncodedCardDetails")
	proto.RegisterType((*Sale)(nil), "Sale")
	proto.RegisterType((*Product)(nil), "Product")
	proto.RegisterType((*Cost)(nil), "Cost")
	proto.RegisterType((*ChargeToken)(nil), "ChargeToken")
	proto.RegisterType((*DiscountCode)(nil), "DiscountCode")
	proto.RegisterType((*DiscountUseRecord)(nil), "DiscountUseRecord")
	proto.RegisterType((*Discount)(nil), "Discount")
}

func init() { proto.RegisterFile("proto/plutus.proto", fileDescriptor_43f31399d60808ca) }

var fileDescriptor_43f31399d60808ca = []byte{
	// 1751 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdd, 0x6e, 0xdb, 0xc8,
	0x15, 0x0e, 0xa9, 0x5f, 0x1e, 0x45, 0xb2, 0x32, 0xf6, 0x7a, 0x15, 0x15, 0xa8, 0x15, 0x36, 0x9b,
	0x18, 0x6e, 0x3b, 0x49, 0xbd, 0x28, 0x90, 0xee, 0x6e, 0x8b, 0xba, 0x92, 0x6c, 0x78, 0x91, 0x55,
	0x8c, 0xb1, 0x9c, 0xa2, 0x05, 0x0a, 0x94, 0x12, 0x27, 0x36, 0x61, 0x89, 0x64, 0xc9, 0x51, 0x62,
	0x6d, 0xfa, 0x22, 0xbd, 0xeb, 0x45, 0x5f, 0xa2, 0x77, 0xbd, 0xee, 0x63, 0xf4, 0x1d, 0x7a, 0x5f,
	0xcc, 0x1f, 0x35, 0xd4, 0x8f, 0xa3, 0xa2, 0xbd, 0xe3, 0x39, 0x73, 0xe6, 0x9c, 0x99, 0x33, 0xdf,
	0xf9, 0x23, 0xa0, 0x38, 0x89, 0x58, 0xf4, 0x22, 0x9e, 0xcc, 0xd8, 0x2c, 0xc5, 0x82, 0x68, 0x1f,
	0x5c, 0x47, 0xd1, 0xf5, 0x84, 0xbe, 0x10, 0xd4, 0x68, 0xf6, 0xee, 0x05, 0x0b, 0xa6, 0x34, 0x65,
	0xde, 0x34, 0x96, 0x02, 0xee, 0x5f, 0x6d, 0x40, 0x97, 0xde, 0x84, 0xa6, 0xa7, 0xc1, 0x84, 0xd1,
	0x84, 0xd0, 0x3f, 0xcd, 0x68, 0xca, 0x10, 0x82, 0x62, 0xec, 0x5d, 0xd3, 0x56, 0xb1, 0x63, 0x1d,
	0x96, 0x88, 0xf8, 0x46, 0x2e, 0x3c, 0x0c, 0x18, 0x9d, 0xa6, 0x17, 0x34, 0xb9, 0xe0, 0x6b, 0x05,
	0xb1, 0x96, 0xe3, 0x21, 0x0c, 0xc5, 0x77, 0x49, 0x34, 0x6d, 0x59, 0x1d, 0xeb, 0xb0, 0x76, 0xdc,
	0xc6, 0xd2, 0x3c, 0xd6, 0xe6, 0xf1, 0x50, 0x9b, 0x27, 0x42, 0x0e, 0x1d, 0x81, 0xcd, 0xa2, 0x96,
	0xfd, 0x49, 0x69, 0x9b, 0x45, 0xe8, 0x29, 0xd4, 0x47, 0xf3, 0xae, 0x97, 0xf8, 0xc3, 0xe8, 0x96,
	0x86, 0xe7, 0xbd, 0x56, 0xb9, 0x63, 0x1d, 0x3a, 0x24, 0xcf, 0x44, 0x87, 0xb0, 0x33, 0x9a, 0x77,
	0x6f, 0xbc, 0xe4, 0x9a, 0x6a, 0xb9, 0x8a, 0x90, 0x5b, 0x66, 0xa3, 0x67, 0x50, 0x1d, 0xcd, 0x2f,
	0x99, 0xc7, 0x68, 0xda, 0x2a, 0x75, 0x0a, 0x87, 0x8d, 0x63, 0xc0, 0xdc, 0x15, 0x82, 0x45, 0xb2,
	0x35, 0x77, 0x04, 0x25, 0xe1, 0x21, 0xf4, 0x03, 0x28, 0xa5, 0xfc, 0xa3, 0x65, 0x75, 0x0a, 0x87,
	0xb5, 0xe3, 0x92, 0x90, 0x26, 0x92, 0x87, 0xf6, 0xa0, 0xc4, 0x22, 0xe6, 0x4d, 0xc4, 0x65, 0x4a,
	0x44, 0x12, 0x99, 0x1f, 0x0b, 0x86, 0x1f, 0x11, 0x14, 0x43, 0x7a, 0xc7, 0xb4, 0x6f, 0xf9, 0xb7,
	0x7b, 0x0d, 0x8f, 0xe4, 0xe1, 0x84, 0x4a, 0xf5, 0x08, 0xfb, 0x50, 0xe6, 0xba, 0xcf, 0x7b, 0xc2,
	0x9d, 0x0e, 0x51, 0x14, 0xea, 0x40, 0x6d, 0x6c, 0xb8, 0xc1, 0x16, 0x8b, 0x26, 0x0b, 0xb5, 0xa0,
	0xe2, 0x53, 0xe6, 0x05, 0x93, 0x54, 0x58, 0x76, 0x88, 0x26, 0xdd, 0x3f, 0xc3, 0xe3, 0x01, 0xfd,
	0x90, 0x39, 0x6c, 0xe0, 0xb1, 0xe0, 0x7d, 0x66, 0x50, 0xdc, 0xe1, 0x96, 0x86, 0xca, 0x9e, 0x24,
	0xd0, 0x17, 0x50, 0x1d, 0xcf, 0x52, 0x16, 0x4d, 0x69, 0xa2, 0x5e, 0xca, 0xc1, 0x5d, 0xc5, 0x20,
	0xd9, 0x12, 0x72, 0xa1, 0xc8, 0xe6, 0xb1, 0xbc, 0x6a, 0xe3, 0xb8, 0x81, 0x33, 0x1b, 0xc3, 0x79,
	0x4c, 0x89, 0x58, 0x73, 0xcf, 0xe1, 0x51, 0x2f, 0x48, 0xc7, 0xd1, 0x2c, 0x64, 0xdd, 0xc8, 0xa7,
	0x6f, 0xbd, 0xc9, 0x8c, 0x72, 0xab, 0xef, 0xf9, 0x87, 0xb6, 0x2a, 0x08, 0xf4, 0x43, 0x00, 0xad,
	0x3a, 0xbb, 0xa3, 0xc1, 0x71, 0x7f, 0x94, 0x57, 0xd5, 0xbf, 0x0b, 0x52, 0x86, 0x1a, 0x60, 0x47,
	0xb7, 0x42, 0x4f, 0x95, 0xd8, 0xd1, 0xad, 0x7b, 0x0b, 0x9f, 0x49, 0xb7, 0xfe, 0x36, 0x60, 0x37,
	0xf2, 0xae, 0xe2, 0x48, 0xf7, 0xb9, 0x36, 0x5c, 0x88, 0x69, 0xd7, 0x1a, 0xac, 0x7b, 0x5c, 0xfb,
	0x0d, 0xd4, 0xcd, 0x13, 0xa5, 0xe8, 0xc7, 0xe0, 0xf8, 0x8a, 0xa1, 0x31, 0x53, 0xc7, 0xa6, 0x08,
	0x59, 0xac, 0xbb, 0xdf, 0xc2, 0xfe, 0xc9, 0x98, 0x9b, 0xd1, 0x02, 0xa9, 0x7e, 0x95, 0x97, 0x50,
	0x9a, 0x85, 0x2c, 0x98, 0x6c, 0x11, 0x54, 0x52, 0xd0, 0xed, 0x40, 0xc3, 0x34, 0x73, 0xde, 0xe3,
	0x8e, 0x09, 0x7c, 0x75, 0x57, 0x3b, 0xf0, 0xdd, 0xcf, 0x60, 0x37, 0x77, 0x10, 0x69, 0xca, 0xfd,
	0x16, 0x1e, 0x71, 0x00, 0x5e, 0xc5, 0x3e, 0x0f, 0x01, 0x65, 0x7f, 0x69, 0x2f, 0xfa, 0x02, 0x60,
	0x26, 0x04, 0x7a, 0x1e, 0xf3, 0x14, 0x22, 0x54, 0x2c, 0x18, 0x0b, 0xee, 0x3f, 0x2d, 0x40, 0x3d,
	0x3a, 0x09, 0xde, 0xd3, 0x64, 0x5b, 0x50, 0xdf, 0x78, 0x61, 0x48, 0x27, 0x03, 0x6f, 0x4a, 0x33,
	0x50, 0x2f, 0x58, 0xe8, 0x97, 0x50, 0x9d, 0x52, 0xe6, 0xf9, 0xdc, 0x6a, 0x41, 0x78, 0xf3, 0x09,
	0x5e, 0x35, 0x80, 0xbf, 0x53, 0x32, 0xfd, 0x90, 0x25, 0x73, 0x92, 0x6d, 0x69, 0x7f, 0x0d, 0xf5,
	0xdc, 0x12, 0x6a, 0x42, 0xe1, 0x96, 0xce, 0xd5, 0x31, 0xf8, 0xe7, 0x02, 0x89, 0xb6, 0x81, 0xc4,
	0xaf, 0xec, 0x57, 0x96, 0x7b, 0x0a, 0xfb, 0xca, 0x54, 0x57, 0x9e, 0x88, 0xd0, 0x34, 0x8e, 0xc2,
	0x94, 0x72, 0x3c, 0x4c, 0x69, 0x9a, 0xf2, 0x20, 0x97, 0x9a, 0x34, 0xc9, 0xe3, 0x7c, 0x1c, 0xf9,
	0x5a, 0x99, 0xf8, 0x76, 0x0f, 0xa0, 0x7e, 0x29, 0xee, 0xbb, 0xc1, 0xb9, 0xee, 0x5b, 0xa8, 0x9e,
	0x7a, 0x29, 0xe3, 0x42, 0x3c, 0xe1, 0x69, 0xc0, 0xf7, 0xa7, 0x9e, 0x02, 0x80, 0x43, 0xf2, 0x4c,
	0xf4, 0x14, 0xaa, 0x71, 0x12, 0xf9, 0xb3, 0x31, 0x4b, 0x5b, 0xb6, 0x70, 0x4b, 0x15, 0x5f, 0x48,
	0x06, 0xc9, 0x56, 0xdc, 0x3f, 0x40, 0x63, 0x40, 0x3f, 0x98, 0x0f, 0x61, 0x86, 0xb5, 0xb5, 0x39,
	0xac, 0xb7, 0x53, 0x7f, 0x00, 0xf5, 0x2c, 0xde, 0x7f, 0x33, 0x5f, 0x03, 0xb8, 0x6f, 0x60, 0xd7,
	0x10, 0xd0, 0x76, 0xb6, 0x3c, 0x84, 0xfb, 0x11, 0x76, 0xcd, 0xac, 0xa5, 0xaf, 0xf0, 0x18, 0x8a,
	0x3c, 0xeb, 0xa9, 0x9d, 0x25, 0x91, 0x72, 0x88, 0x60, 0xfd, 0x3f, 0x93, 0x96, 0x0f, 0x45, 0xce,
	0xe6, 0xc8, 0x0d, 0x67, 0xd3, 0x91, 0x3a, 0xa9, 0x43, 0x14, 0xc5, 0x11, 0x40, 0xef, 0xe2, 0xef,
	0xa2, 0x90, 0xa9, 0xdc, 0xaf, 0x49, 0xb5, 0xf2, 0x3b, 0xea, 0x25, 0xaa, 0x00, 0x68, 0x92, 0x63,
	0x6f, 0xfc, 0x7e, 0x2c, 0x4a, 0x80, 0x43, 0xf8, 0xa7, 0xfb, 0x17, 0x0b, 0xaa, 0x99, 0x5b, 0x96,
	0x43, 0x6e, 0x0f, 0x4a, 0x54, 0x20, 0x40, 0x01, 0x53, 0x10, 0xa2, 0x90, 0xf0, 0x58, 0x91, 0x79,
	0x48, 0x7c, 0xf3, 0x43, 0xc6, 0x34, 0x49, 0xa3, 0x50, 0x55, 0x47, 0x45, 0x71, 0x0d, 0xf1, 0x4d,
	0x14, 0x52, 0x65, 0x52, 0x12, 0xdc, 0x4b, 0x93, 0x68, 0xec, 0xb1, 0x20, 0x0a, 0x5b, 0x25, 0xe5,
	0xa5, 0xd7, 0x8a, 0x41, 0xb2, 0x25, 0xf7, 0x8f, 0x50, 0xd5, 0x5c, 0x7e, 0x27, 0xcf, 0xf7, 0x13,
	0x9a, 0xa6, 0x1a, 0xef, 0x8a, 0x14, 0x78, 0x0f, 0xd8, 0x3c, 0xc3, 0x7b, 0xc0, 0x44, 0x44, 0xa5,
	0xbc, 0x8a, 0xaa, 0x33, 0x4a, 0x82, 0xdf, 0xfe, 0xfb, 0x20, 0xd6, 0xb7, 0xff, 0x3e, 0x88, 0xdd,
	0x7f, 0x58, 0xe0, 0x64, 0xbe, 0x5f, 0xb9, 0xbe, 0x7e, 0x25, 0x7b, 0xf3, 0x2b, 0x2d, 0x62, 0xb7,
	0x60, 0x56, 0x91, 0x17, 0x50, 0xfd, 0x10, 0xb0, 0x1b, 0xbe, 0x41, 0x98, 0xab, 0x1d, 0xef, 0xe2,
	0x7e, 0xc8, 0x43, 0xd1, 0xe7, 0xbc, 0x9e, 0x4c, 0xdd, 0x24, 0x13, 0x42, 0xaf, 0xc0, 0x19, 0x27,
	0xd4, 0x63, 0xd4, 0x3f, 0x61, 0xca, 0x25, 0xf7, 0x25, 0xdc, 0x85, 0xb0, 0xfb, 0x11, 0xd0, 0xaa,
	0xe6, 0x8d, 0xa0, 0x79, 0x06, 0x0d, 0x7a, 0x17, 0x07, 0x89, 0x70, 0xaa, 0x40, 0x88, 0xc4, 0xce,
	0x12, 0x37, 0x87, 0xe3, 0xc2, 0xe6, 0x00, 0xf9, 0x5b, 0x01, 0x8a, 0x22, 0x67, 0x2c, 0xbb, 0x2e,
	0x77, 0x1f, 0xfb, 0xbf, 0xb8, 0x0f, 0xdf, 0x29, 0xb3, 0x39, 0xdf, 0x59, 0xf8, 0xf4, 0xce, 0x4c,
	0x18, 0x75, 0xf4, 0xa3, 0x17, 0xc5, 0x7b, 0x99, 0x5d, 0x95, 0x02, 0x80, 0x79, 0xab, 0xd2, 0x76,
	0xb9, 0xa7, 0xbc, 0x29, 0xf7, 0xa0, 0x2f, 0xa1, 0xee, 0x9b, 0x75, 0xb7, 0x55, 0x59, 0x57, 0x6a,
	0xf3, 0x32, 0xe8, 0x10, 0x9c, 0xac, 0x61, 0x6a, 0x55, 0xc5, 0x11, 0x60, 0x81, 0x2b, 0xb2, 0x58,
	0x44, 0x4f, 0xa1, 0x3c, 0x16, 0x3d, 0x44, 0xcb, 0x11, 0x62, 0x0f, 0xb1, 0xd1, 0x46, 0x12, 0xb5,
	0x26, 0x73, 0x75, 0x92, 0xd0, 0x70, 0x3c, 0x1f, 0x46, 0x17, 0xde, 0xbc, 0x05, 0x3a, 0x57, 0x1b,
	0x4c, 0x97, 0x40, 0x45, 0x9d, 0x3f, 0x0b, 0x5e, 0xcb, 0x08, 0x5e, 0xa3, 0xb7, 0xb0, 0x73, 0xbd,
	0x85, 0xc8, 0x74, 0x51, 0xaa, 0xdf, 0xa1, 0x84, 0xbb, 0x51, 0xca, 0x88, 0x60, 0xb9, 0x5f, 0x41,
	0x91, 0x53, 0x1c, 0x69, 0xde, 0x94, 0x5f, 0x50, 0xa8, 0xb4, 0x88, 0xa2, 0x50, 0x9b, 0xfb, 0x5a,
	0x1e, 0x42, 0x69, 0xcd, 0x68, 0xf7, 0xef, 0x16, 0xd4, 0x8c, 0xdb, 0xac, 0xcb, 0x3b, 0xab, 0x05,
	0xd1, 0x2c, 0x79, 0x85, 0x7c, 0xc9, 0x7b, 0x09, 0x75, 0x1d, 0x49, 0xd2, 0xb3, 0xc5, 0x15, 0xcf,
	0xe6, 0x05, 0xfe, 0x87, 0x78, 0xfb, 0xb7, 0x05, 0x0f, 0xcd, 0x17, 0x5e, 0x39, 0xfc, 0x4b, 0x01,
	0xc3, 0x64, 0x1b, 0xd8, 0x4b, 0x41, 0xf4, 0x13, 0x28, 0xd0, 0xd0, 0xdf, 0x02, 0xec, 0x5c, 0x4c,
	0xb8, 0xc1, 0xbb, 0xbb, 0x4a, 0x69, 0xaa, 0x5a, 0x79, 0x4d, 0xa2, 0x67, 0x50, 0x9c, 0xa5, 0x6a,
	0xaa, 0xa8, 0x1d, 0xa3, 0x0c, 0x88, 0x57, 0x29, 0x25, 0x74, 0x1c, 0xf1, 0x22, 0xc5, 0xd7, 0xb3,
	0x0e, 0xa1, 0xbc, 0xe8, 0x10, 0xd0, 0x81, 0x76, 0x79, 0x45, 0xc5, 0x85, 0xde, 0xac, 0xbc, 0xef,
	0xfe, 0x7e, 0xd1, 0xf8, 0x66, 0xfa, 0xf8, 0x1c, 0xe5, 0xb1, 0x2d, 0x1a, 0x44, 0xdb, 0xe3, 0x55,
	0xd3, 0x1e, 0xcd, 0x57, 0x8b, 0xa2, 0x3d, 0x9a, 0xbb, 0x1f, 0xa1, 0xaa, 0x75, 0xa3, 0x27, 0x2a,
	0xe9, 0x5a, 0x22, 0x88, 0x17, 0xd1, 0x64, 0xe4, 0xdc, 0x16, 0x54, 0x62, 0x9a, 0x8c, 0xa9, 0xaa,
	0x7c, 0x16, 0xd1, 0xa4, 0x01, 0xc6, 0xc2, 0x46, 0x30, 0x16, 0xf3, 0x60, 0x3c, 0x3a, 0x32, 0x7a,
	0x08, 0x6e, 0x04, 0x01, 0x94, 0xdf, 0x0c, 0xfa, 0x57, 0x97, 0xfd, 0xe6, 0x03, 0x54, 0x07, 0x87,
	0xf4, 0xbb, 0x57, 0x84, 0xf4, 0x07, 0xc3, 0xa6, 0x75, 0xd4, 0x05, 0x27, 0x4b, 0x2a, 0xa8, 0x0a,
	0xc5, 0xc1, 0xd5, 0xeb, 0xd7, 0xcd, 0x07, 0xc8, 0x81, 0x52, 0x8f, 0x9c, 0x9c, 0x0e, 0x9b, 0x16,
	0xdf, 0x7c, 0x79, 0x7e, 0x36, 0xe8, 0xf7, 0x9a, 0x36, 0xaa, 0x41, 0xe5, 0xe2, 0xe4, 0xbc, 0xf7,
	0xe6, 0x6a, 0xd8, 0x2c, 0x70, 0xe9, 0xde, 0x9b, 0x41, 0xbf, 0x59, 0x3c, 0x7a, 0xbe, 0x00, 0x90,
	0xb6, 0x77, 0x39, 0x3c, 0x19, 0x9e, 0x77, 0x9b, 0x0f, 0xc4, 0x96, 0x3e, 0xe9, 0x0a, 0x6b, 0xc7,
	0xff, 0xaa, 0x40, 0xf9, 0x42, 0x8c, 0xd5, 0xe8, 0x25, 0x3c, 0x34, 0x3b, 0x11, 0xb4, 0x87, 0xd7,
	0x34, 0x26, 0x6d, 0x03, 0xf0, 0xe8, 0xd7, 0xb0, 0x6f, 0x8a, 0x9c, 0x26, 0xd1, 0x54, 0x4e, 0x22,
	0xa8, 0x8d, 0x37, 0x8e, 0x62, 0x39, 0x0d, 0xaf, 0xa0, 0x7d, 0x46, 0x59, 0x46, 0xbf, 0x79, 0xa7,
	0xdf, 0x4c, 0x76, 0x5a, 0x38, 0xd7, 0x79, 0xe5, 0x76, 0xf6, 0xa0, 0xb3, 0x69, 0x67, 0xd6, 0x6b,
	0xec, 0xe1, 0x35, 0x8d, 0x59, 0x4e, 0xcb, 0x4f, 0x61, 0xa7, 0x47, 0x27, 0x94, 0x51, 0xa3, 0x42,
	0xdf, 0x63, 0xf4, 0x00, 0x6a, 0x03, 0xfa, 0x21, 0xeb, 0x62, 0x1d, 0xac, 0x3f, 0xdb, 0x72, 0x4a,
	0x40, 0x4f, 0xa0, 0xa2, 0x7a, 0x51, 0xb4, 0x83, 0xf3, 0x5d, 0xa9, 0x16, 0xe9, 0x40, 0xe5, 0x8c,
	0xca, 0xfd, 0x0d, 0x9c, 0xeb, 0x98, 0xb5, 0xc4, 0x73, 0xa8, 0x2a, 0x89, 0x14, 0xed, 0xe2, 0xd5,
	0x5f, 0x18, 0xed, 0xb2, 0x64, 0xa2, 0xe7, 0x00, 0x72, 0x9e, 0x11, 0xdb, 0x10, 0x5e, 0x19, 0x70,
	0xb4, 0xc6, 0xaf, 0xa1, 0x66, 0x8c, 0x13, 0x68, 0x77, 0xcd, 0x70, 0xd1, 0xfe, 0x1c, 0x6f, 0x18,
	0x03, 0x8e, 0xa1, 0xb1, 0x18, 0xe0, 0xc5, 0xbb, 0x20, 0xbc, 0x32, 0xd1, 0xb7, 0x73, 0xb5, 0x03,
	0x9d, 0xc0, 0xe3, 0x85, 0xc8, 0xca, 0x84, 0x8a, 0xd7, 0x4e, 0xae, 0x4b, 0x2a, 0x9e, 0x40, 0xb5,
	0x17, 0x85, 0xf4, 0x3e, 0x47, 0xfd, 0x02, 0x50, 0x57, 0x24, 0xcd, 0x5c, 0xb2, 0xdc, 0xc3, 0x6b,
	0xe6, 0xbf, 0x76, 0xbe, 0x66, 0xa2, 0x9f, 0xc1, 0xce, 0x19, 0x65, 0x39, 0xd6, 0x0e, 0xce, 0x4f,
	0x96, 0xcb, 0x5b, 0x7e, 0x05, 0x7b, 0x6f, 0xbd, 0x49, 0xe0, 0x2f, 0xdb, 0x43, 0x78, 0x65, 0xf0,
	0x6f, 0xe7, 0x79, 0x72, 0x82, 0x3f, 0x81, 0xfd, 0x33, 0xca, 0xf2, 0x93, 0xb0, 0xac, 0xd8, 0x9f,
	0xe3, 0xf5, 0xf3, 0x71, 0xbb, 0x81, 0xf3, 0x82, 0x3f, 0x17, 0x73, 0x27, 0x5d, 0x3a, 0xc0, 0xca,
	0xc1, 0x97, 0xb6, 0x8d, 0xca, 0x22, 0x5d, 0x7e, 0xf9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x82,
	0x01, 0x11, 0x91, 0x47, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlutusClient is the client API for Plutus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlutusClient interface {
	NewCardToken(ctx context.Context, in *NewCardTokenRequest, opts ...grpc.CallOption) (*CardToken, error)
	NewCardTokenFromNative(ctx context.Context, in *NewCardTokenNativeRequest, opts ...grpc.CallOption) (*CardToken, error)
	GetCardTokenOfCustomerByID(ctx context.Context, in *CardTokenByID, opts ...grpc.CallOption) (*CardToken, error)
	GetCardTokenOfCustomerByCustomer(ctx context.Context, in *CardTokenByCustomer, opts ...grpc.CallOption) (*CardToken, error)
	DeleteCardToken(ctx context.Context, in *CardTokenByID, opts ...grpc.CallOption) (*CardToken, error)
	NewFastSale(ctx context.Context, in *FastSale, opts ...grpc.CallOption) (*Sale, error)
	NewSale(ctx context.Context, in *NewSaleRequest, opts ...grpc.CallOption) (*Sale, error)
	GetSale(ctx context.Context, in *SaleIDRequest, opts ...grpc.CallOption) (*Sale, error)
	GetSales(ctx context.Context, in *SalesFilterRequest, opts ...grpc.CallOption) (*Sales, error)
	UpdateSale(ctx context.Context, in *SaleUpdateRequest, opts ...grpc.CallOption) (*Sale, error)
	DeliverSale(ctx context.Context, in *DeliverSaleRequest, opts ...grpc.CallOption) (*DeliverChannelResponse, error)
	ChargeSaleByID(ctx context.Context, in *ChargeSaleRequest, opts ...grpc.CallOption) (*ChargeToken, error)
	ChargeSaleWithNativeToken(ctx context.Context, in *ChargeWithNativeToken, opts ...grpc.CallOption) (*ChargeToken, error)
	DoneSale(ctx context.Context, in *SaleIDRequest, opts ...grpc.CallOption) (*Sale, error)
	CreateDiscountCode(ctx context.Context, in *DiscountCodeRequest, opts ...grpc.CallOption) (*DiscountCode, error)
	GetDiscountCode(ctx context.Context, in *DiscountCodeID, opts ...grpc.CallOption) (*DiscountCode, error)
	ValidateDiscountCode(ctx context.Context, in *DiscountCodeValue, opts ...grpc.CallOption) (*DiscountCodeExist, error)
	GetActiveDiscountCodes(ctx context.Context, in *ActiveDiscountsRequest, opts ...grpc.CallOption) (*DiscountCodes, error)
	DeleteDiscountCode(ctx context.Context, in *DiscountCodeID, opts ...grpc.CallOption) (*DiscountCodes, error)
}

type plutusClient struct {
	cc *grpc.ClientConn
}

func NewPlutusClient(cc *grpc.ClientConn) PlutusClient {
	return &plutusClient{cc}
}

func (c *plutusClient) NewCardToken(ctx context.Context, in *NewCardTokenRequest, opts ...grpc.CallOption) (*CardToken, error) {
	out := new(CardToken)
	err := c.cc.Invoke(ctx, "/Plutus/NewCardToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) NewCardTokenFromNative(ctx context.Context, in *NewCardTokenNativeRequest, opts ...grpc.CallOption) (*CardToken, error) {
	out := new(CardToken)
	err := c.cc.Invoke(ctx, "/Plutus/NewCardTokenFromNative", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) GetCardTokenOfCustomerByID(ctx context.Context, in *CardTokenByID, opts ...grpc.CallOption) (*CardToken, error) {
	out := new(CardToken)
	err := c.cc.Invoke(ctx, "/Plutus/GetCardTokenOfCustomerByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) GetCardTokenOfCustomerByCustomer(ctx context.Context, in *CardTokenByCustomer, opts ...grpc.CallOption) (*CardToken, error) {
	out := new(CardToken)
	err := c.cc.Invoke(ctx, "/Plutus/GetCardTokenOfCustomerByCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) DeleteCardToken(ctx context.Context, in *CardTokenByID, opts ...grpc.CallOption) (*CardToken, error) {
	out := new(CardToken)
	err := c.cc.Invoke(ctx, "/Plutus/DeleteCardToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) NewFastSale(ctx context.Context, in *FastSale, opts ...grpc.CallOption) (*Sale, error) {
	out := new(Sale)
	err := c.cc.Invoke(ctx, "/Plutus/NewFastSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) NewSale(ctx context.Context, in *NewSaleRequest, opts ...grpc.CallOption) (*Sale, error) {
	out := new(Sale)
	err := c.cc.Invoke(ctx, "/Plutus/NewSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) GetSale(ctx context.Context, in *SaleIDRequest, opts ...grpc.CallOption) (*Sale, error) {
	out := new(Sale)
	err := c.cc.Invoke(ctx, "/Plutus/GetSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) GetSales(ctx context.Context, in *SalesFilterRequest, opts ...grpc.CallOption) (*Sales, error) {
	out := new(Sales)
	err := c.cc.Invoke(ctx, "/Plutus/GetSales", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) UpdateSale(ctx context.Context, in *SaleUpdateRequest, opts ...grpc.CallOption) (*Sale, error) {
	out := new(Sale)
	err := c.cc.Invoke(ctx, "/Plutus/UpdateSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) DeliverSale(ctx context.Context, in *DeliverSaleRequest, opts ...grpc.CallOption) (*DeliverChannelResponse, error) {
	out := new(DeliverChannelResponse)
	err := c.cc.Invoke(ctx, "/Plutus/DeliverSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) ChargeSaleByID(ctx context.Context, in *ChargeSaleRequest, opts ...grpc.CallOption) (*ChargeToken, error) {
	out := new(ChargeToken)
	err := c.cc.Invoke(ctx, "/Plutus/ChargeSaleByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) ChargeSaleWithNativeToken(ctx context.Context, in *ChargeWithNativeToken, opts ...grpc.CallOption) (*ChargeToken, error) {
	out := new(ChargeToken)
	err := c.cc.Invoke(ctx, "/Plutus/ChargeSaleWithNativeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) DoneSale(ctx context.Context, in *SaleIDRequest, opts ...grpc.CallOption) (*Sale, error) {
	out := new(Sale)
	err := c.cc.Invoke(ctx, "/Plutus/DoneSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) CreateDiscountCode(ctx context.Context, in *DiscountCodeRequest, opts ...grpc.CallOption) (*DiscountCode, error) {
	out := new(DiscountCode)
	err := c.cc.Invoke(ctx, "/Plutus/CreateDiscountCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) GetDiscountCode(ctx context.Context, in *DiscountCodeID, opts ...grpc.CallOption) (*DiscountCode, error) {
	out := new(DiscountCode)
	err := c.cc.Invoke(ctx, "/Plutus/GetDiscountCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) ValidateDiscountCode(ctx context.Context, in *DiscountCodeValue, opts ...grpc.CallOption) (*DiscountCodeExist, error) {
	out := new(DiscountCodeExist)
	err := c.cc.Invoke(ctx, "/Plutus/ValidateDiscountCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) GetActiveDiscountCodes(ctx context.Context, in *ActiveDiscountsRequest, opts ...grpc.CallOption) (*DiscountCodes, error) {
	out := new(DiscountCodes)
	err := c.cc.Invoke(ctx, "/Plutus/GetActiveDiscountCodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plutusClient) DeleteDiscountCode(ctx context.Context, in *DiscountCodeID, opts ...grpc.CallOption) (*DiscountCodes, error) {
	out := new(DiscountCodes)
	err := c.cc.Invoke(ctx, "/Plutus/DeleteDiscountCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlutusServer is the server API for Plutus service.
type PlutusServer interface {
	NewCardToken(context.Context, *NewCardTokenRequest) (*CardToken, error)
	NewCardTokenFromNative(context.Context, *NewCardTokenNativeRequest) (*CardToken, error)
	GetCardTokenOfCustomerByID(context.Context, *CardTokenByID) (*CardToken, error)
	GetCardTokenOfCustomerByCustomer(context.Context, *CardTokenByCustomer) (*CardToken, error)
	DeleteCardToken(context.Context, *CardTokenByID) (*CardToken, error)
	NewFastSale(context.Context, *FastSale) (*Sale, error)
	NewSale(context.Context, *NewSaleRequest) (*Sale, error)
	GetSale(context.Context, *SaleIDRequest) (*Sale, error)
	GetSales(context.Context, *SalesFilterRequest) (*Sales, error)
	UpdateSale(context.Context, *SaleUpdateRequest) (*Sale, error)
	DeliverSale(context.Context, *DeliverSaleRequest) (*DeliverChannelResponse, error)
	ChargeSaleByID(context.Context, *ChargeSaleRequest) (*ChargeToken, error)
	ChargeSaleWithNativeToken(context.Context, *ChargeWithNativeToken) (*ChargeToken, error)
	DoneSale(context.Context, *SaleIDRequest) (*Sale, error)
	CreateDiscountCode(context.Context, *DiscountCodeRequest) (*DiscountCode, error)
	GetDiscountCode(context.Context, *DiscountCodeID) (*DiscountCode, error)
	ValidateDiscountCode(context.Context, *DiscountCodeValue) (*DiscountCodeExist, error)
	GetActiveDiscountCodes(context.Context, *ActiveDiscountsRequest) (*DiscountCodes, error)
	DeleteDiscountCode(context.Context, *DiscountCodeID) (*DiscountCodes, error)
}

func RegisterPlutusServer(s *grpc.Server, srv PlutusServer) {
	s.RegisterService(&_Plutus_serviceDesc, srv)
}

func _Plutus_NewCardToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCardTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).NewCardToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/NewCardToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).NewCardToken(ctx, req.(*NewCardTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_NewCardTokenFromNative_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCardTokenNativeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).NewCardTokenFromNative(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/NewCardTokenFromNative",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).NewCardTokenFromNative(ctx, req.(*NewCardTokenNativeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_GetCardTokenOfCustomerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardTokenByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).GetCardTokenOfCustomerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/GetCardTokenOfCustomerByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).GetCardTokenOfCustomerByID(ctx, req.(*CardTokenByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_GetCardTokenOfCustomerByCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardTokenByCustomer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).GetCardTokenOfCustomerByCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/GetCardTokenOfCustomerByCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).GetCardTokenOfCustomerByCustomer(ctx, req.(*CardTokenByCustomer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_DeleteCardToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardTokenByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).DeleteCardToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/DeleteCardToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).DeleteCardToken(ctx, req.(*CardTokenByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_NewFastSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FastSale)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).NewFastSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/NewFastSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).NewFastSale(ctx, req.(*FastSale))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_NewSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).NewSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/NewSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).NewSale(ctx, req.(*NewSaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_GetSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).GetSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/GetSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).GetSale(ctx, req.(*SaleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_GetSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalesFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).GetSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/GetSales",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).GetSales(ctx, req.(*SalesFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_UpdateSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).UpdateSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/UpdateSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).UpdateSale(ctx, req.(*SaleUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_DeliverSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverSaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).DeliverSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/DeliverSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).DeliverSale(ctx, req.(*DeliverSaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_ChargeSaleByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeSaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).ChargeSaleByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/ChargeSaleByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).ChargeSaleByID(ctx, req.(*ChargeSaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_ChargeSaleWithNativeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeWithNativeToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).ChargeSaleWithNativeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/ChargeSaleWithNativeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).ChargeSaleWithNativeToken(ctx, req.(*ChargeWithNativeToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_DoneSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).DoneSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/DoneSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).DoneSale(ctx, req.(*SaleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_CreateDiscountCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscountCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).CreateDiscountCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/CreateDiscountCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).CreateDiscountCode(ctx, req.(*DiscountCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_GetDiscountCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscountCodeID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).GetDiscountCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/GetDiscountCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).GetDiscountCode(ctx, req.(*DiscountCodeID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_ValidateDiscountCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscountCodeValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).ValidateDiscountCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/ValidateDiscountCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).ValidateDiscountCode(ctx, req.(*DiscountCodeValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_GetActiveDiscountCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveDiscountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).GetActiveDiscountCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/GetActiveDiscountCodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).GetActiveDiscountCodes(ctx, req.(*ActiveDiscountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plutus_DeleteDiscountCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscountCodeID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlutusServer).DeleteDiscountCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plutus/DeleteDiscountCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlutusServer).DeleteDiscountCode(ctx, req.(*DiscountCodeID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plutus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Plutus",
	HandlerType: (*PlutusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewCardToken",
			Handler:    _Plutus_NewCardToken_Handler,
		},
		{
			MethodName: "NewCardTokenFromNative",
			Handler:    _Plutus_NewCardTokenFromNative_Handler,
		},
		{
			MethodName: "GetCardTokenOfCustomerByID",
			Handler:    _Plutus_GetCardTokenOfCustomerByID_Handler,
		},
		{
			MethodName: "GetCardTokenOfCustomerByCustomer",
			Handler:    _Plutus_GetCardTokenOfCustomerByCustomer_Handler,
		},
		{
			MethodName: "DeleteCardToken",
			Handler:    _Plutus_DeleteCardToken_Handler,
		},
		{
			MethodName: "NewFastSale",
			Handler:    _Plutus_NewFastSale_Handler,
		},
		{
			MethodName: "NewSale",
			Handler:    _Plutus_NewSale_Handler,
		},
		{
			MethodName: "GetSale",
			Handler:    _Plutus_GetSale_Handler,
		},
		{
			MethodName: "GetSales",
			Handler:    _Plutus_GetSales_Handler,
		},
		{
			MethodName: "UpdateSale",
			Handler:    _Plutus_UpdateSale_Handler,
		},
		{
			MethodName: "DeliverSale",
			Handler:    _Plutus_DeliverSale_Handler,
		},
		{
			MethodName: "ChargeSaleByID",
			Handler:    _Plutus_ChargeSaleByID_Handler,
		},
		{
			MethodName: "ChargeSaleWithNativeToken",
			Handler:    _Plutus_ChargeSaleWithNativeToken_Handler,
		},
		{
			MethodName: "DoneSale",
			Handler:    _Plutus_DoneSale_Handler,
		},
		{
			MethodName: "CreateDiscountCode",
			Handler:    _Plutus_CreateDiscountCode_Handler,
		},
		{
			MethodName: "GetDiscountCode",
			Handler:    _Plutus_GetDiscountCode_Handler,
		},
		{
			MethodName: "ValidateDiscountCode",
			Handler:    _Plutus_ValidateDiscountCode_Handler,
		},
		{
			MethodName: "GetActiveDiscountCodes",
			Handler:    _Plutus_GetActiveDiscountCodes_Handler,
		},
		{
			MethodName: "DeleteDiscountCode",
			Handler:    _Plutus_DeleteDiscountCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plutus.proto",
}
